using UnityEngine;
using System.Collections;

public class NPCRetainersSexScenes {

	static string HESHE = "", HISHER = "", HIMHER = "", heshe = "", hisher = "", himher = "";
	//////////////////////////////////// non corrupt - good relation ////////////////////////////////////

	////mc handjob to NPC - MC Neut, NPC w vag

	public static string Good_HJ_2NPC_V(){ // MC neut handjob to npc w vag
		checkGender ();

		return"Today you felt like a charitative master. You had a great need to pleasure one lucky worker that may come in your way. You walked through the hallways of your castle, calmly looking if any of your servants appeared. You were about to return to your chambers and call someone for yourself one " + heshe + " showed up. One of your favorites.\n \nYou called " + himher + " by " + hisher + " name and waited in place while " + heshe + " approached you. You hugged " + himher + " by the side once " + heshe + " was near enough and whispered sweet nothings into " + hisher + " ear while " + heshe + " giggled.\n \n" + HESHE + " looked at you, smiling. " + HESHE + " loved to see you in a good mood, and told you so. You replied that the feeling was mutual while you caressed " + hisher + " back and kissed " + himher + " on the lips. As you kept kissing, your hand traveled under " + hisher + " clothes to caress " + hisher + " crotch softly. " + HESHE + " gasped at the touch, breaking the kiss, and tightened " + hisher + " embrace.\n \n" + HESHE + " kissed your chin while your fingers continued to play with " + hisher + " parts until they started getting wet. " + HISHER + " lack of underwear allowed you to feel the soft skin of " + hisher + " humid lips. Your fingers slid between them, letting you be welcome inside the warm walls of " + hisher + " insides. You felt " + hisher + " knees starting to weaken and pressed " + hisher + " body against yours with more force to prevent " + himher + " from falling to the ground.\n \n" + HESHE + " opened " + hisher + " legs more to give you all the space you needed. You thanked " + himher + " and gave " + himher + " a peck on the cheek without stopping your hands. You inserted another finger in " + himher + " and moved it in and out, alongside wih the other, until there was enough space for a third one. The movements of your fingers made " + himher + " moan your name desperately.  Although you had allowed " + himher + " to do so in situations like this one, you could clearly see how shy " + heshe + " was about it. " + HISHER + " face was redder than before, embarrassed of calling you in such a personal way. You kissed " + himher + " lips one more time and made your fingers travel deeper inside " + himher + ". " + HESHE + " moaned in your lips and shuddered one last time before coming, damping your fingers with " + hisher + " orgasm.\n \nYou helped " + himher + " adjust " + hisher + " clothing and let " + himher + " resume " + hisher + " duties. " + HESHE + " thanked you for the wonderful gift of your touch and left happier than before to " + hisher + " work, not without turning at you and smiling one last time. You smiled at " + himher + " as well and left.";
			
	}

	public static string Good_HJ_2NPC_D(){ // mc neut handjob to  npc w dick 
		checkGender ();
		return "You went to the library and saw one of your dearest servants admiring the many decorations you have over your chimney. You took a seat in the couch in front of it letting "+himher+" continue without saying a word. "+HESHE+" didn’t notice you until the wind pushed down one of the decorations. As it fell to the floor "+heshe+" turned back and looked at you in surprise and apologized for not being quick enough to catch the fallen item. You shook your head and told "+himher+" not to worry about it. Then you gave two pats to your lap, gesturing "+himher+" to take a sit on it.\n \n"+HESHE+" smiled and blushed notoriously, but sat without hesitation.  "+HESHE+" caressed your face softly, expressing with "+hisher+" touches how much "+heshe+" misses you on the daily. You didn’t stop "+himher+", and let "+himher+" get close to your face to plant a soft kiss on your lips. You returned the gesture, kissing "+himher+" back and caressing "+hisher+" chest over "+hisher+" clothes. Your touches made "+himher+" sigh quietly and rest "+hisher+" head over your shoulder. You felt how "+hisher+" eyes looked at you with longing. You couldn’t blame "+himher+", it was rare for you to have time to spend with any of your servants. But you were there now.\n \nYou kissed "+hisher+" neck tenderly, while one of your hands palmed "+hisher+" crotch with no remorse. You could hear how "+hisher+" breathing changed, getting more agitated as your caresses kept going. "+HESHE+" hugged you by the neck, and begged to your ear for you to continue, bargaining for "+hisher+" wish by delivering kisses to your face.\n \nYou finally reached under "+hisher+" clothes and wrapped "+hisher+" dick with your fingers, pulling "+hisher+" half-mast hurriedly while you kissed "+himher+" on the lips. As it became fully erect, "+hisher+" dick became lubricated with precum, damping "+hisher+" clothes with the liquid and making it easier for you to caress "+himher+".\n \nThe library soon filled with "+hisher+" moans. You could feel "+hisher+" body twitching over you. You knew "+hisher+" body so well you were sure "+hisher+" climax was not far away. While your hands continued touching "+hisher+" erection, your tongue traveled from "+hisher+" shoulder to "+hisher+" ear, reaching "+hisher+" lobe and biting eat upon contact. "+HESHE+" shuddered one last time and came on your hand with a loud moan, drenching "+hisher+" clothes with "+hisher+" spunk.\n \n"+HISHER+" face reddened furiously. "+HESHE+" stood up and apologized for almost making your clothes dirty. You shook your head once again, cleaning your hand with a napkin you were carrying. When you stood up you told "+himher+" to continue with whatever "+heshe+" was doing after "+heshe+" changed. After saying that you left the library. ";
	}


	public static string Good_HJ_2NPC_F(){ // mc neut handjob to npc w dick and vag 
		checkGender ();
		return "You visit the servant’s chambers and see one of your servants entering the bathrooms. " + HESHE + " is completely naked as " + heshe + " steps inside a tub to start washing " + himher + "self. The first thing " + heshe + " does is pour soapy water into " + hisher + " entire body making it glisten against the light. You can see the foam forming as " + hisher + " hands diligently wash " + hisher + " crotch; lifting " + hisher + " dick with one hand to wash " + hisher + " cunt with the other.  You get closer and announce yourself. " + HESHE + " looks at you embarrassed, and leaving " + hisher + " crotch alone, yet " + heshe + " asks you if you need any help with anything. You shake your head and tell " + himher + " this time you were going to help " + himher + ". " + HESHE + " laughs shyly at that comment but opens " + hisher + " arms ready to receive you.\n \nYou take some steps closer, entering the tub and letting " + himher + " embrace you. You kiss " + himher + " on the lips and " + heshe + " brushes with " + hisher + " wet fingers your hair, revealing your face and kissing your forehead while you touch " + hisher + " butt and make " + hisher + " dick rub against you. " + HESHE + " lets out a soft moan after you rubbed yourself against " + himher + " long enough. You see " + himher + " get more embarrassed by " + hisher + " own arousal, but you tell " + himher + " not to worry, and that you’ll take matters into your own hands.\n \n" + HESHE + " smiles at you and gives you a small peck on the lips. You turn " + himher + " over, so " + hisher + " back is facing you. This makes it easier for you to grab " + hisher + " dick in your hand and caress it while your fingers enter " + hisher + " cunt, aided by the soap from before. You tell " + himher + " how much you enjoy the beauty of " + hisher + " body and how you always appreciated how beautiful " + heshe + " smelt. " + HESHE + " replays in a sweet panting voice how all of that is thanks to your kind generosity with " + himher + ". You notice the gratefulness on " + hisher + " voice and can’t stop yourself from kissing " + hisher + " neck. " + HESHE + " giggles because your sweet kisses tickle " + himher + ", but " + hisher + " laughs sound a bit weird as they are interrupted by " + hisher + " moans.\n \nThe foam on " + hisher + " dick increases with your caresses as it does the one on " + hisher + " pussy. " + HESHE + " is moaning as loud as " + heshe + " can. You love hearing all the noises " + heshe + " makes when you wash " + himher + ". More than getting " + himher + " clean you want to help " + himher + " reach " + hisher + " orgasm. And thanks to your skill " + heshe + " comes in a matter of minutes, drenching your hands with cum. You help " + himher + " once more, removing all the soap and cum from " + hisher + " body with the water in a nearby bucket. And then kissing " + himher + " on the cheek as a goodbye, you promise to see " + himher + " again some other time, and leave.\n";
			
	}

	///////////////////////////////////////
	////npc handjob to MC- npc Neut

	public static string Good_HJ_2MC_V(){ // npc hj to mc w vag 
		checkGender ();
		return "You enter to your room and see one of your servants waiting for you. When you enter " + heshe + " looks at you and greets you politely as always. " + HESHE + " leaves whatever " + heshe + " was doing to entertain " + himher + "self and approaches you to kiss your hand. You smile at " + himher + " and compliment " + himher + " on " + hisher + " work, in which you are always aware of " + hisher + " performance, but must importantly you compliment " + hisher + " looks. " + HESHE + " averts your gaze and blushes, " + heshe + " tells you that you always look your best, and loves having " + hisher + " sight on you. You smile and ask " + himher + " if " + heshe + " always is looking at you. " + HESHE + " says that only when it is proper but wishes " + heshe + " did when it is not. You pat " + himher + " on the head and assure " + himher + " this was " + hisher + " lucky day. You take your clothes of while walking to your bead, leaving them everywhere on the floor. You sit on the bed and command your servant to look at you, " + heshe + " does it with pleasure, blushing intensely, and licking " + hisher + " lips as " + heshe + " did so.\n \n" + HESHE + " then asked you if it was appropriate for " + himher + " to touch, you allow " + himher + " to, and open more your legs. " + HESHE + " seats besides you and uses the tip of " + hisher + " fingers to caress all the area of your crotch, always stopping on your clitoris to press it in circles before continuing to caress the rest, and then back at it. Your breath starts shifting after just a little, becoming more agitated.\n \nYour servant caresses your leg while two of " + hisher + " fingers enter your cunt. Caressing the walls of your vagina and getting moist with your fluids. When " + heshe + " noticed " + heshe + " could move freely inside you, " + heshe + " started ramming " + hisher + " fingers into you as fast as " + heshe + " could. You couldn’t stop moaning by then. " + HESHE + " licked your neck and shoulders while playing with your nipples to increase your pleasure. Confident in that you wouldn’t mind at the state you are in.\n \nYour moans were telling how close you were to reach climax, so your servant started moving " + hisher + " fingers in a scissoring motion to help you get there quickly. You couldn’t believe how great " + hisher + " fingers felt inside you. That was the only thought that occupied your mind while you were being touched. Finally you came, getting " + hisher + " hand and your bed sheets completely wet.\n \n" + HESHE + " carried you to a couch nearby and let you rest there while " + heshe + " called some other servants to take care of cleaning the bed. Lastly " + heshe + " thanked you for letting " + himher + " touch you like that. You were satisfied and watched " + himher + " until " + heshe + " left.";
			
	}

	public static string Good_HJ_2MC_D(){ // npc hj to mc w dick 
		checkGender ();
		return "You enter to the servant’s chambers. In there, one of your servants was putting clothes on in the common room, dressing for the day’s work. When you enter, " + heshe + " didn’t notice you and continue getting ready. You watched as " + hisher + " beautiful figure became hidden with layers of fabric. You thought that in any other servant getting dressed wouldn’t be such a big deal, but this one moved in a different way, almost sensual. You couldn’t stop watching.\n \nAfter getting " + hisher + " workwear ready, " + heshe + " finally looked back and saw you there, sitting on the chair against the wall. " + HESHE + " blushed and covered " + hisher + " smile with " + hisher + " hand. " + HESHE + " apologized for not noticing sooner, suggesting that " + heshe + " would have given you a show if " + heshe + " knew. You smile and admit that to you that was a show already. " + HESHE + " looks at your crotch and tells you that they can see that. You don’t have to take a peak to know you have an erection, you are very aware of it.\n \nWithout you asking, your servant comes and sits next to you, releasing your erected cock from your clothing and caressing its base with " + hisher + " entire hand. You sigh loudly and " + heshe + " understands that " + heshe + " should continue. " + HISHER + " hand moves though the entire length of your cock at a fast speed. " + HESHE + " spits on your dick to decrease the friction between " + hisher + " hand and your cock, your precum is helping " + himher + " with that as well. You can see determination on " + hisher + " face. " + HISHER + " eyes have not stopped watching your dick, making sure " + heshe + " touches you how you like it. You smile at that and decide to distract " + himher + " a little, taking " + himher + " by the chin and pulling " + himher + " for a deep kiss. " + HESHE + " closed " + hisher + " eyes to enjoy such demonstration of affect but " + hisher + " hand did not stop. Your pleasure kept being " + hisher + " top priority.\n \nWhen you broke the kiss " + heshe + " gave you another two more, kissing then your temple and after that your neck. All those places were being drown with small kisses, helping the throbs of your cock increase. Finally you came on " + hisher + " hand without a warning and " + heshe + " immediately cleaned your crotch and " + hisher + " hand with a napkin " + heshe + " had in " + hisher + " pocket.\n \nYou thanked " + himher + " for giving you such wonderful service, but " + heshe + " only blushed and told you not to worry about thanking " + himher + ". You approached " + himher + " to kiss " + himher + " on the lips one last time and left.";
			
	}

	public static string Good_HJ_2MC_F(){ // npc hj to mc w dick and vag 
		checkGender ();
		return "You enter your wine cellar where one of your servants is carefully looking at the many distinct bottles on your collection. You notice how the entire cellar has been kept pristine clean and pride at your excellent talent for ‘recruiting’ new ‘work force’.  You take one of the bottles in a nearby cabinet, it’s one of the oldest ones and call to your servant, who had not notice you until then. " + HESHE + " looks at you and smiles, genuinely happy to see you. " + HESHE + " sees the bottle in your hands and asks you if you would want " + himher + " to server you a glass. You tell " + himher + " to serve you two.\n \n" + HESHE + " leaves to fetch the glasses while you take seat in a bench far from the entrance. Your servant does not take long to bring with " + himher + " two glasses and serve them in front of you. " + HESHE + " jokingly tells you that " + heshe + " could have serve you twice if you were so thirsty. You laugh and offer " + himher + " the other glass. " + HESHE + " looks surprised but takes it anyway and waits for you to drink first, before drinking " + hisher + " wine " + himher + "self. The wine tasted delicious, you barely felt the alcohol, but your servant was less tolerant of it, and looked dizzy already.\n \nYou knew " + heshe + " was definitely drunk when " + heshe + " approached you and kissed your lips, sitting by your side and embracing you. You kissed " + himher + " too with the same energy and sat on " + hisher + " lap, wrapping " + himher + " with your legs. You broke the kiss only to serve you both more wine. After " + heshe + " drank " + hisher + " entire glass " + heshe + " started kissing your neck and chestwhile you were drinking. Both " + hisher + " hands went to your crotch where " + heshe + " took your dick with one hand and started fingering your cunt from behind you with the other.\n \nYou moaned when you felt " + hisher + " cold hands entering and touching you. With " + hisher + " movements " + heshe + " made you hard in no time. You continued to kiss " + himher + " desperately wanting " + himher + " to continue. " + HISHER + " fingers opened and closed inside you while moving in circles, the humidity of your cunt started mixing with the trails of precum that oozed from the tip of your dick. You could feel how your cheeks blushed intensely, you realized how hot they were when " + heshe + " kissed them and " + hisher + " lips felt like ice against your flesh.\n \n" + HISHER + " cold hands kept caressing you rapidly, until the double stimuli of your cunt and dick made you climax. Your semen dirtied " + hisher + " workwear and your fluids completely drenched " + hisher + " lap. " + HESHE + " just smiled at this and gave you a sweet peck before helping you regain your composure and adjust your clothes. Finally " + heshe + " served you one more cup before you left with it.";
			
	}

	///////////////////////////////////////
	// mc bj to npc 


	public static string Good_BJ_2NPC_D(){ // mc bj to npc w dick 
		checkGender ();
		return "You were on your way to your room when you spotted one of your favorite servants hidden behind one of the hallway’s pillars. You quietly approached " + himher + " to see what " + heshe + " was doing. You found out that " + heshe + " was pleasuring " + himher + "self, forcefully pulling " + hisher + " dick, biting on " + hisher + " arm to keep " + hisher + " panting from being listened.\t\n \nYou touched " + hisher + " busy arm to call for " + hisher + " attention. " + HESHE + " stopped suddenly and looked at you scared. When " + heshe + " realized it was you " + heshe + " sighed and smiled embarrassed. You reassure " + himher + " that you love what " + heshe + " was doing and are only here to help " + himher + ". While saying that you place your palm over " + hisher + " damp erection. You feel how it’s already twitching, seeking release.\n \n" + HESHE + " tells you that you don’t have to bother helping " + himher + ", it might be too much receiving help from " + hisher + " master. But you pay no attention to those details, those didn’t matter if it was about " + himher + ". You put yourself in front of " + himher + " and cup " + hisher + " dick with both hands, then you lick the head of " + hisher + " dick, cleaning all the droplets of cum that were already out. Once clean you allowed it inside your mouth, massaging it with your tongue while you gave a few sucks. The sight of seeing you blowing " + himher + " was already too much for " + himher + ", you could notice in the way " + heshe + " was panting. " + HESHE + " did not tried to hide " + hisher + " voice anymore, as being seen with you was not embarrassing for " + himher + " as it would be being seen alone pleasuring " + himher + "self.\n \nYou loved the way " + heshe + " sounded and made " + hisher + " voice louder by continuing sucking " + himher + " off with diligence. Little by little you allowed " + hisher + " dick to enter your throat until the entirety of " + hisher + " dick was inside your mouth and you could push no more. It was then that " + heshe + " pressed your head against " + himher + " to cum inside your mouth. You swallowed everything " + heshe + " offered you, and were happy to do so. " + HESHE + " apologized softly for coming in your mouth but you reassured " + himher + " it was ok. You stood up, cleaning your mouth, and ordered " + himher + " to get back to " + hisher + " duties and " + heshe + " obeyed immediately.";
			
	}

	public static string Good_BJ_2NPC_V(){ //  MC BJ to npc w vag
		checkGender ();
		return "You were walking through your castle when you passed by the dining room where noises where coming from. Curious, you decided to inspect it. You saw one of your loyal servants looking at the cutlery on the table that was set for your next dinner, which still was a few hours away. You watched " + himher + " in silence for a long time. Your eyes were focused on the way " + hisher + " ass looked as " + heshe + " walked around the table. You loved the way " + hisher + " buttocks rocked from side to side, and couldn’t help yourself from imagining how it’ll be to eat " + hisher + " pussy.\n \nThen you realized there was no need to fantasize about it. You carefully close the door behind you and approached " + himher + " by the back, touching " + hisher + " crotch under " + hisher + " clothing. " + HESHE + " gasped and turned " + hisher + " head. When " + heshe + " saw it was you " + heshe + " gave a relieved sigh which was followed by a moan, as your fingers enter inside " + himher + ". You kept fingering " + himher + " until " + heshe + " became wet. Then you sat " + himher + " on the table were " + heshe + " lay down over the tableware, opening " + hisher + " legs for you.\n \nYou removed " + hisher + " underwear and frenetically kissed " + hisher + " pussy, spreading " + hisher + " fluids all around the area. Your hands separated the lips of " + hisher + " cunt so your tongue could directly caress " + hisher + " entrance, making space for itself, sliding in as far as you could. You couldn’t get enough of that taste. Your tongue moved all ways just to get more of it.\n \n" + HESHE + " couldn’t stop moaning and moving " + hisher + " legs around to try not to be as noisy. " + HISHER + " hands were clasped to the tablecloth, to help " + himher + " keep the little composure " + heshe + " had left. Satiating your thirst for " + himher + " you decided to give " + himher + " release and started sucking on " + hisher + " clit with a tremendous force. " + HESHE + " yelled " + hisher + " lungs out and came, spraying you with " + hisher + " fluid.\n \nAfter coming back to " + hisher + " senses, " + heshe + " cleaned your face carefully with the table cloth and excused " + hisher + "self.  " + HESHE + " felt responsible for ruining the table and determined to go fetch someone to fix it. You nod, and kiss " + hisher + " neck to say goodbye before " + heshe + " left in a hurry.";
			
	}

	public static string Good_BJ_2NPC_F(){ // MC BJ to npc w futa
		checkGender ();
		return "You decided to wonder over your horse shed. The barn had just been cleaned and the smell of pristine hay filled the air. You heard a soft noise coming from one of the empty stalls. You get closer and see one of your servants in deep sleep. You recognize " + himher + " immediately, and that is the only reason you are not scolding " + himher + " for sleeping in a random place. This particular servant had been the protagonist of many of your fantasies, that for one reason or another you haven’t been able to fulfill, but this was about to change right now.\n \nYou entered the stall and lay beside " + himher + " on the hay, caressing " + hisher + " cheek with the back of your hand until " + heshe + " woke up. " + HESHE + " recognizes you immediately and lands a soft kiss on your lips, sheepishly smiling at you once it was over. You give " + himher + " a side smile and camly started to untie " + hisher + " workwear. " + HESHE + " helps you undress " + himher + " while you position yourself over " + hisher + " body. " + HESHE + " hugs you with minimal force, allowing you to move from " + hisher + " embrace and kiss " + hisher + " lips, chin, chest, and so on, little by little going downwards until you reached " + hisher + " crotch.\n \nYou had " + hisher + " half erection in front of you. You suppose " + heshe + " was having very nice dreams to reach this state. You kiss where " + hisher + " dick joined with " + hisher + " pussy, licking everything around while one of your hands caressed " + hisher + " dick. You couldn’t figure out where to pleasure first, but figured " + hisher + " pussy was closer. You explored " + hisher + " cave with the entirety of your tongue and then gave a long luck from it until the tip of " + hisher + " cock, where you let it enter your mouth.\n \n" + HESHE + " moaned sweetly, playing with your hair without the minimum intention of stopping you. " + HISHER + " taste was better than anything you’d imagined. This was a dream come true. You kept changing your attention from one sex to the other until " + heshe + " finally came on in front of you, both fluids combining on your face. You cleaned yourself with your sleeve and covered " + himher + " with some hay to let " + himher + " continue resting. You left having satisfied your hunger.";
			
	}

	public static string Good_BJ_2MC_D(){ // NPC bj to MC w dick 
		checkGender ();
		return "You were walking through the hallways when one of your servants comes to you. " + HESHE + " camly takes your hand and lures you into an empty room. You could infer by " + hisher + " slightly unusual behavior that " + heshe + " was horny.  And judging by the little looks " + heshe + " gives you while " + heshe + " takes you to a chair, you are correct. You let " + himher + " sit you in said chair, it was one of your finest, so it was not uncomfortable anyway, not that that mattered to you in this kind of situations.\n \n" + HESHE + " kneels in front of you and waits for you to give " + himher + " a signal. You nod and " + heshe + " happily removes the clothes from your crotch, taking out your limp dick with both " + hisher + " hands. " + HESHE + " gives it many kisses before stroking it with care as if it were the most wonderful thing on earth. " + HISHER + " soft hands upon your sensitive skin felt like a relaxing massage. " + HESHE + " now accompanied those caresses with small licks, barely using the tip of " + hisher + " tongue.\n \nYou thought that was adorable, and slightly squished " + hisher + " cheeks with your hands. " + HESHE + " blushed by the act, but that only encouraged " + himher + " to use " + hisher + " tongue more. You were thankful for that. Despite how wonderful " + hisher + " wet appendage felt, you wanted more. " + HESHE + " could see that in your face and decided it was best to house your cock inside " + hisher + " mouth. " + HESHE + " let it inside slowly, afraid " + hisher + " mouth wouldn’t have enough space for it, and after a little while " + heshe + " had the head of your cock safely inside. " + HESHE + " tried to suck it, but it was too big for " + himher + " to apply any pressure. It was then that " + heshe + " resolved that the only way to pleasure you was having your cock ramming into " + hisher + " throat.\n \n" + HESHE + " took out your dick and told you about " + hisher + " thoughts, and how " + heshe + " would need you to do most of the movements. You nodded again and grabbed " + hisher + " head by the nape, smashing your dick all the way inside, taking no mind of the gagging sounds your servant was making. " + HESHE + " had told you not to stop no matter what until you were satisfied and you were going to comply that petition. You move your hips faster every time, reaching deep inside " + himher + ", until you finally come. Your seed fills " + hisher + " mouth and " + heshe + " swallows every last drop. You sigh completely relieved. You knew " + heshe + " got off just by doing that to you, that’s why you liked " + himher + " so much. " + HESHE + " put your clothes back on and excused " + himher + "self before leaving.";
			
	}


	//////////////////////////////////// non corrupt - bad relation ////////////////////////////////////












	//////////////////////////////////// corrupt ////////////////////////////////////









	static void checkGender(){
		if (NPCCharList.CharRetainers [WorldControl.idx].charGender == NPCData.CharGender.MALE) {
			HESHE = "He"; HISHER = "His"; HIMHER = "Him"; heshe = "he"; hisher = "his"; himher = "her";
		} else {
			HESHE = "She"; HISHER = "Her"; HIMHER = "Her"; heshe = "she"; hisher = "her"; himher = "her";
		}
	}




}
