using UnityEngine;
using System.Collections;
using UnityEngine.UI;

public class VivicaSex : MonoBehaviour {

	static int iCelia; 
	public Text Board;

	static string mcpronoun; 

	public Canvas endTurnPanel; 
	public Canvas panSexPanel;


	static int iVivica; 


	// ADD A BRO SIS


	public void sexScenes(int selector){
		switch (selector) {
		case 0:
			sexScene1 ();
			break;
		case 1:
			sexScene2 ();
			break;
		case 2:
			sexScene3 ();
			break;
		case 3:
			sexScene4 ();
			break;
		case 4:
			sexScene5 ();

			break;

		}

	}

	void sexScene1(){
		GameControl.actualArousal = 0;

		if (NPCCharList.CharFollower [iVivica].corruptionStage >= 4)
		{
			Board.text = "You went to sleep just like any other day, as you went into deep sleep. But this time is different. You think that you’re having a wet dream, because you can only feel horny as hell. You have a dream that some kind of demon is fucking you, using you like some kind of giant sex toy while you’re stripped, unable to do anything else but to be used by this monster to her liking. You can only think that this is amazing, but it feels real, perhaps too real. Its not that its something bad, but somehow it wakes you up, covered in sweat.\n\nSlowly you can only wake up,finding out something moving through your sheets and attached to you. As you move them aside, you can see that your sister Vivica is there, enjoying herself against your groin as if it were of her property. Her moans of pleasure echo across the whole room. You ask her what she is doing, but she only pushes you back with one of her legs while she is pressing her hands all over your belly and pinching you with her nails. <i>“I’m just taking something that I want, my "+ mcpronoun +". And this little demon wants her daily dose of her "+ mcpronoun +" juice”</i> She moans while she plays with her own body while she does. It seems that she isn’t taking a no for an answer.";
			if (GameControl.dick1Size > 0) {
				Board.text += "You can feel your "+ GameControl.mcDickType.toDescription() +" dick being ridden by her tight pussy, as you can feel her inner walls massaging your "+ GameControl.mcDick1Name.toDescription() +" cock as she moves up and down from you. She is holding herself from your own legs while she rides your "+ GameControl.mcDick1Name.toDescription() +" shaft like there is no tomorrow, her own tail rubbing her perky breasts as her face is one of pure pleasure. <i>“I just couldn’t wait for the morning before feeling more of you!”</i> you can hear from her as her cunt juices flow through your whole groin and thighs. The tightness of her pussy and the warm of her insides is getting you to pant profusely, her moaning and thrashing all over your cock is too much for your body to contain. She arches towards you, pressing her slim body while her groin grinds your dick over and over again.\n\nThis is the best way of starting a day, or at least you can’t think of any other way right now, as Vivica is serving herself almost on a plate as your breakfast. You grab her by her thighs and start thrusting your "+ GameControl.mcDickType.toDescription() +" shaft, against her cunt with force. You can feel how her insides almost welcome you with more trembling and massages all over your cock, causing her to open her eyes wide as her moans increase in speed, matching each thrust of your thick dick against her sensitive insides. <i>“Harder! Harder, my "+ mcpronoun +"! I want you to fill your sister!”</i> She says out loud, as you can’t help but cum, holding her in place with both of your hands. You can feel your cock convulsing on her twat, filling her belly with your thick seed and painting her inner walls with your sperm, until she is full of you and starts leaking into the bedsheets that are close to you. You can feel how that pushes her over the edge, her face distorting into one of pure bliss while her cunt spasms wildly, sign of that she is having her own orgasm, her body trembling as your juices mix and fill the room with the scent of sex.\n\n <i>“I knew that my "+ mcpronoun +"’s cock would love some sisterly love… I do, by the way”</i> She says as she starts to stand up from her place, as she starts floating through the window that is in your bedroom, her own fluids dripping as she moves away from the bed. She cleans herself with a bit of magic before floating away just like she does. She doesn’t even helped you with the cleaning of the place. You can’t help but sigh, its not like you have to do the cleaning, but you need a bath right now.";
			} else {
				Board.text += "You can feel your own cunt rubbing against her own vagina, both of your juices mixing with glee as both of you are thrashing and moving from the pleasure. She is holding your legs as she keeps rubbing herself, her clit pushing against your naughty flesh. <i>“I just couldn’t wait for the morning before feeling more of you!”</i> she says while you can feel her own juices flowing through your thighs. Your body trembles from the delight that she is causing you more and more, as her moans only add to the excitement that your body can hold. She starts using her tail, rubbing your body more and more as if it were a hand, teasing you with care.\n\nYou can only think that this is one of the best ways of waking up, as your sister enjoys serving herself on your bed as a breakfast. You can’t help but play with your own "+ GameControl.mcBreast1Name.toDescription() +" chest as your own clit thrusts against her, sending you ripples of pleasure across your whole body as she moans wildly from your sensations. <i>“Let me hear you cum!”</i> She cries out loud as you can’t help but cum, holding her legs tightly while your own twat trembles from all the sensations she is causing you, soaking the whole bed and the sheets. You can hear her girly screams of pleasure as she is having an orgasm on her own, as her whole body spasms alongside her pussy, creating a small rivulet of vaginal juices from both of you, until you’re completely spent.\n\n<i>“I knew that my "+ mcpronoun +" would love some sisterly love…”</i> She says as she starts to stand up from her place, as she starts floating through the window that is in your bedroom, her own fluids dripping as she moves away from the bed. She cleans herself with a bit of magic before floating away just like she does. She doesn’t even helped you with the cleaning of the place. You can’t help but sigh, its not like you have to do the cleaning, but you need a bath right now.\n";
			}

		} 
		else 
		{
			Board.text = "You were asleep on this ocassion, as something is bothering you a bit while you were on your bed. You think that you’re having a wet dream, because you can only feel horny as hell. You have a dream that some kind of demon is fucking you, using you like some kind of giant sex toy while you’re stripped, unable to do anything else but to be used by this monster to her liking.\n\nYou open your eyes slowly, only to find out something moving through your sheets. As you move them aside, you can see that your sister Vivica is there, enjoying herself against your groin. Her moans of pleasure echo across the whole room. You ask her what she is doing. <i>“I’m sorry, my "+ mcpronoun +". Its just that I… couldn’t resist to have you. You can’t blame me for that”</i> She moans while she plays with her own body while she does.";
			if (GameControl.dick1Size > 0) {
				Board.text += "You can feel your "+ GameControl.mcDickType.toDescription() +" dick being ridden by her tight pussy, as you can feel her inner walls massaging your "+ GameControl.mcDick1Name.toDescription() +" cock as she moves up and down from you. She is holding herself from your own legs while she rides your "+ GameControl.mcDick1Name.toDescription() +" shaft like there is no tomorrow, her own tail rubbing her perky breasts as her face is one of pure pleasure. <i>“I just couldn’t wait for the morning before feeling more of you!”</i> you can hear from her as her cunt juices flow through your whole groin and thighs. The tightness of her pussy and the warm of her insides is getting you to pant profusely, her moaning and thrashing all over your cock is too much for your body to contain. She arches towards you, pressing her slim body while her groin grinds your dick over and over again.\n\nThis is the best way of starting a day, or at least you can’t think of any other way right now, as Vivica is serving herself almost on a plate as your breakfast. You grab her by her thighs and start thrusting your "+ GameControl.mcDickType.toDescription() +" shaft, against her cunt with force. You can feel how her insides almost welcome you with more trembling and massages all over your cock, causing her to open her eyes wide as her moans increase in speed, matching each thrust of your thick dick against her sensitive insides. <i>“Harder! Harder, my "+ mcpronoun +"! I want you to fill your sister!”</i> She says out loud, as you can’t help but cum, holding her in place with both of your hands. You can feel your cock convulsing on her twat, filling her belly with your thick seed and painting her inner walls with your sperm, until she is full of you and starts leaking into the bedsheets that are close to you. You can feel how that pushes her over the edge, her face distorting into one of pure bliss while her cunt spasms wildly, sign of that she is having her own orgasm, her body trembling as your juices mix and fill the room with the scent of sex.\n\n <i>“I knew that my "+ mcpronoun +"’s cock would love some sisterly love… I do, by the way”</i> She says as she starts to stand up from her place, as she starts floating through the window that is in your bedroom, her own fluids dripping as she moves away from the bed. She cleans herself with a bit of magic before floating away just like she does. She doesn’t even helped you with the cleaning of the place. You can’t help but sigh, its not like you have to do the cleaning, but you need a bath right now.";
			} else {
				Board.text += "You can feel your own cunt rubbing against her own vagina, both of your juices mixing with glee as both of you are thrashing and moving from the pleasure. She is holding your legs as she keeps rubbing herself, her clit pushing against your naughty flesh. <i>“I just couldn’t wait for the morning before feeling more of you!”</i> she says while you can feel her own juices flowing through your thighs. Your body trembles from the delight that she is causing you more and more, as her moans only add to the excitement that your body can hold. She starts using her tail, rubbing your body more and more as if it were a hand, teasing you with care.\n\nYou can only think that this is one of the best ways of waking up, as your sister enjoys serving herself on your bed as a breakfast. You can’t help but play with your own "+ GameControl.mcBreast1Name.toDescription() +" chest as your own clit thrusts against her, sending you ripples of pleasure across your whole body as she moans wildly from your sensations. <i>“Let me hear you cum!”</i> She cries out loud as you can’t help but cum, holding her legs tightly while your own twat trembles from all the sensations she is causing you, soaking the whole bed and the sheets. You can hear her girly screams of pleasure as she is having an orgasm on her own, as her whole body spasms alongside her pussy, creating a small rivulet of vaginal juices from both of you, until you’re completely spent.\n\n<i>“I knew that my "+ mcpronoun +" would love some sisterly love…”</i> She says as she starts to stand up from her place, as she starts floating through the window that is in your bedroom, her own fluids dripping as she moves away from the bed. She cleans herself with a bit of magic before floating away just like she does. She doesn’t even helped you with the cleaning of the place. You can’t help but sigh, its not like you have to do the cleaning, but you need a bath right now.\n";
			}
				
		}
		endTurnFun ();
	}

	void sexScene2(){
		GameControl.actualArousal = 0;

		if (NPCCharList.CharFollower [iVivica].corruptionStage >= 4) {
			Board.text = "This time, both of you are practicing some magic combat. You know that since she absorbed that powerful energy well, you worry that you’re no match for her, but at least you can try to keep up with her as an sparring partner. But you knot that this is more for you than its for her, and that is not a bad thing after all. You are using basic spells, as you know that any other spell from her would be quite detrimental to your health. But you are sure that if you ask her, you’re being a weakling for needing that kind of treatment, but you’re sure that she worries about your health and doesn’t push too much on the subject.\n\nYou dodge one of her Destructive spells as you try to inflict some of the Persuasion spells. She avoids the enchantment but turns to see you and invokes the same spell, hitting you with more force than you thought were using. You land on your knees, your body feeling searing hot as you tremble and pant. Your sister looks quite confused and floats in your direction, floating close to you as it sees you with curiosity. <i>“As expected, I knew that it would happen eventually. It was just a matter of time”</i> You can bet on it, as you can’t help but start removing your clothes by instinct, nothing more for the moment. But when she sees what you’re doing, she smiles a bit and positions herself over you. <i>“Well, well, well… Look who is eager to be fucked now. How does it feel? Because I can remember it as bright as way”</i> She says as she runs a hand through your groin area, as you uncover it. Your face is getting red only from the scent that you’re feeling from her. She pushes you with both hands against the floor as she uses a leg to held you in place as she positions herself better.\n";
			if (GameControl.dick1Size > 0) {
				Board.text += "She grabs your "+ GameControl.mcDick1Name.toDescription() +" cock with one of her hands, stroking it as she places herself between your legs and start giving it soft licks. Your hands tremble from the fact that you can only think on facefucking her, but you contain as she is doing her job. Her tongue is quite soft and wet, as her hand deftly strokes your cock while she gives you a lusty look. <i>“Am I doing it right, my "+ mcpronoun +"? It seems so…”</i> She says as she licks from its base to the tip of your "+ GameControl.mcDickType.toDescription() +" cock.\n\nYour cock greets her with a small load of precum that stains her hand, which she cleans dutifully. <i>“This taste is from my "+ mcpronoun +"’s cum. I can’t get tired of it”</i> She says as she introduces your cock inside her mouth, her tongue circling around it with ease, trying to tease its contents to get inside her mouth. Her warmness and wetness are amazing, as she licks and bites carefully every part of it. <i>“Don’t keep me waiting. I can handle it.”</i> She says in a sexy tone as you can’t stand anymore, your penis trembling and twitching from the pleasure as it unloads its contents into her hungry mouth. Her throat is being filled with your strong-scented cum as she holds your dick with both hands, trying her best not to spill a drop from your spunk. You can feel your whole body being overflowed with pleasure, as your little winged sister is giving you the blowjob of your life.\n\nAfter a couple of seconds of continued loading, you finally feel your balls churning from its emptiness, as your sister did her best, but it wasn’t enough as some of it soaked her chest and face. <i>“Its so thick… Its making me a bit dizzy”</i> She says with a smile as she gulped most of it. <i>“If this is what happens when I overstep, maybe I should do it more often”</i> She cleans your dick with her tongue, your oversensitive flesh twitches at the feeling of her tongue once more, until you’re finally clean. After that, you can’t help but lay on your back. <i>“Let’s leave it like this for the moment.”</i> You can hear her giggling as you pass out from the spell and its conclusion.";
			} else {
				Board.text += "She spreads your legs with both of her hands, using her tongue to lick your twat softly, enjoying your womanhood with glee. You fight the urge to plunge her face into your crotch and try to use her as a sex toy, as she tries her best to pay what she has done. Her tongue is quite soft and wet, as her hands deftly rubs your cunt’s lips and inner walls while she gives you a lusty look. <i>“Am I doing it right, my "+ mcpronoun +"? It seems so…”</i> Shesays as she licks as far as she can, inside your pussy.\n\nYou can feel your pussy flooding with your own juices, the thought of your sister giving you a good licking is making you wetter than you thought at first. All that femspunk is being cleaned by Vivica with pleasure. <i>“This taste is from my "+ mcpronoun +" juices. I can’t get tired of it”</i> She says as she plays with your clit with her tongue, circling it with it, its softness and wetness sending you over the edge rather quickly, probably due to the strength of the spell that she sling at you. <i>“I wonder how much of your juices can flow out of it”</i> She says in an inquisitive tone mixed with delight. After that, you can’t stand anymore, as you cum all over her face, your inner walls convulsing in a rhythmic manner while a surge of pleasure fills every nerve, every part of you. Her mouth is flowing with your vaginal juices as she enjoys slurping them at the best of her ability. The spells powers are too much for you, as the fact that your little winged sister is licking you in this way is driving you mad.\n\nAfter a couple of seconds of continued orgasming, you finally feel your whole groin spent even when its on fire, as your sister mouth and nose are covered in your female-scented cum. <i>“Its so bitter… I can’t gulp it all”</i> But that doesn’t stop her from trying. <i>“If this is what happens when I overstep, maybe I should do it more often”</i> She cleans the rests of your fluids with her tongue. After that, you can’t help but lay on your back. <i>“Let’s leave it like this for the moment.”</i> You can hear her giggling as you pass out from the spell and its conclusion.";
			}
		} else {
			Board.text = "This time, both of you are practicing some magic combat. You know that since she has been a bit debilitated by the fact that she broke herself free from the source of her magic, she is still quite skilled in the art of spellcasting, but you know that you’ve been improving too on your own and you can stand her in training. Both of you are hurling basics spells, as you don’t want to damage each other in this kind of practicing.\n\nYou dodge one of her destructive spells as you try to inflict some of the Persuasion spells. She avoids the enchantment but turns to see you and invokes the same spell, hitting you with more force than you thought were using. You land on your knees, your body feeling searing hot as you tremble and pant. Your sister looks quite worried and floats in your direction, holding you in her arms as she helps you to see her a bit. <i>“Sorry! I think I overdid it!”</i> You can bet on it, as you can’t help but start removing your clothes by instinct, nothing more for the moment. But when she sees what you’re doing, she smiles a bit and positions herself over you. <i>“If I’m the reason that you’re here, then let me take care of it…”</i> She says as she runs a hand through your groin area, as you uncover it. Your face is getting red only from the scent that you’re feeling from her.";
			if (GameControl.dick1Size > 0) {
				Board.text += "She grabs your "+ GameControl.mcDick1Name.toDescription() +" cock with one of her hands, stroking it as she places herself between your legs and start giving it soft licks. Your hands tremble from the fact that you can only think on facefucking her, but you contain as she is doing her job. Her tongue is quite soft and wet, as her hand deftly strokes your cock while she gives you a lusty look. <i>“Am I doing it right, my "+ mcpronoun +"? It seems so…”</i> She says as she licks from its base to the tip of your "+ GameControl.mcDickType.toDescription() +" cock.\n\nYour cock greets her with a small load of precum that stains her hand, which she cleans dutifully. <i>“This taste is from my "+ mcpronoun +"’s cum. I can’t get tired of it”</i> She says as she introduces your cock inside her mouth, her tongue circling around it with ease, trying to tease its contents to get inside her mouth. Her warmness and wetness are amazing, as she licks and bites carefully every part of it. <i>“Don’t keep me waiting. I can handle it.”</i> She says in a sexy tone as you can’t stand anymore, your penis trembling and twitching from the pleasure as it unloads its contents into her hungry mouth. Her throat is being filled with your strong-scented cum as she holds your dick with both hands, trying her best not to spill a drop from your spunk. You can feel your whole body being overflowed with pleasure, as your little winged sister is giving you the blowjob of your life.\n\nAfter a couple of seconds of continued loading, you finally feel your balls churning from its emptyness, as your sister did her best, but it wasn’t enough as some of it soaked her chest and face. <i>“Its so thick… Its making me a bit dizzy”</i> She says with a smile as she gulped most of it. <i>“If this is what happens when I overstep, maybe I should do it more often”</i> She cleans your dick with her tongue, your oversensitive flesh twitches at the feeling of her tongue once more, until you’re finally clean. After that, you can’t help but lay on your back. <i>“Let’s leave it like this for the moment.”</i> You can hear her giggling as you pass out from the spell and its conclusion.\n";
			} else {
				Board.text += "She spreads your legs with both of her hands, using her tongue to lick your twat softly, enjoying your womanhood with glee. You fight the urge to plunge her face into your crotch and try to use her as a sex toy, as she tries her best to pay what she has done. Her tongue is quite soft and wet, as her hands deftly rubs your cunt’s lips and inner walls while she gives you a lusty look. <i>“Am I doing it right, my "+ mcpronoun +"? It seems so…”</i> Shesays as she licks as far as she can, inside your pussy.\n\nYou can feel your pussy flooding with your own juices, the thought of your sister giving you a good licking is making you wetter than you thought at first. All that femspunk is being cleaned by Vivica with pleasure. <i>“This taste is from my "+ mcpronoun +" juices. I can’t get tired of it”</i> She says as she plays with your clit with her tongue, circling it with it, its softness and wetness sending you over the edge rather quickly, probably due to the strength of the spell that she sling at you. <i>“I wonder how much of your juices can flow out of it”</i> She says in an inquisitive tone mixed with delight. After that, you can’t stand anymore, as you cum all over her face, your inner walls convulsing in a rhythmic manner while a surge of pleasure fills every nerve, every part of you. Her mouth is flowing with your vaginal juices as she enjoys slurping them at the best of her ability. The spells powers are too much for you, as the fact that your little winged sister is licking you in this way is driving you mad.\n\nAfter a couple of seconds of continued orgasming, you finally feel your whole groin spent even when its on fire, as your sister mouth and nose are covered in your female-scented cum. <i>“Its so bitter… I can’t gulp it all”</i> But that doesn’t stop her from trying. <i>“If this is what happens when I overstep, maybe I should do it more often”</i> She cleans the rests of your fluids with her tongue. After that, you can’t help but lay on your back. <i>“Let’s leave it like this for the moment.”</i> You can hear her giggling as you pass out from the spell and its conclusion.";
			}
		}
		endTurnFun ();
	}


	void sexScene3(){
		GameControl.actualArousal = 0;

		if (NPCCharList.CharFollower [iVivica].corruptionStage >= 4) {
			Board.text = "You’ve been always wondering about her tail and all the capabilities of it. You’ve heard of the transformative abilities that the demons have with them and its a surprise that she is still having the same tail even when she lost the contact with the being that transformed her in the first place. So you decided to ask her, something that makes her turn towards her own ass and touch her tail. <i>“Oh, this? It has a lot of transformative capacities. Of course, most of them are used for fucking mortal in different kind of ways”</i> You raise one eyebrow at the word, so you ask her to show you.\n\nWhen you say that, she smiles wickedly and walks towards you as she pins you against the wall that is behind you with force, almost causing you some pain on the process. <i>“I have been waiting for you to ask me this, you know? I would love to show you how a demon does it”</i> And with that, she starts undressing your clothes as her tongue trails across your neck. She is quite good at undressing you, so good that you wonder if she has been training in her mind. <i>“Just relax and let your dear sister take the reins of the ride… I’ve been dreaming of this for a long time”</i> She says in a whisper close to your ear, as she is still floating close to you. And well, that answer your question from before. You can even say that she is using magic to pin you in place, not that you need it if they ask you.";
			if (GameControl.dick1Size > 0) {
				Board.text += "You can feel her tail teasing your dick, soaking itself in your own fluids but with more energy than you expected. <i>“One of its abilities is to transform into this…”</i> She says as it converts into an onahole, that it seems to be made from the same material that her tail is made. <i>“I’m so eager to use it with you..”</i> You hear from her as that new made-up onahole is pressing against your erect "+ GameControl.mcDick1Name.toDescription() +" dick with force, as she seems to like it more rough than you thought she would. <i>“You like it rough? I do and I hope you too”</i>  You can feel that somehow the mere touch of that is causing you to lose your mind to the pleasure. You are sure that it must be linked to that strange entity energies and influences. But its rubbing and wetness is something ecstatic for you. <i>“They say that a demon tail can make someone cum just from the first rub of it. It seems to be lost its full power…”</i> \n\nAfter saying that, she teases its entrance against you, as her black warm onahole is engulfing slowly your "+ GameControl.mcDick1Name.toDescription() +" dick with lustful insistence. You can see that your sister’s face is completely red, as if it were a cock connected to her. <i>“I can feel it as if it were my own cunt…, if that’s what you’re thinking…”</i> She says between pants, as you hug her just to feel her girly body against your "+ GameControl.mcBreast1Name.toDescription() +" chest for a second. And without further warning, she plunges her dark onahole to engulf your "+ GameControl.mcDickType.toDescription() +" cock completely, the sensation already sending you over the edge. The tightness of her onahole is wonderful, as it feels as if someone is massaging your cock manually while suctioning with force over and over again. You can’t help but moan wildly as she almost forces you to ravage her tail with savagery.\n\nYou can’t last long to such demonic power, as you can’t resist to fill that onahole with your whole load as you cum hard, the pleasure coursing through you like a bolt of electricity. Your body trembles as her onahole is milking you dry more and more, your orgasm lasting more and more with every suck of it, until you can feel that you’re completely empty of spunk. \n\nWhen you finally feel spent, you hold yourself from the wall behind you, telling her that her tail is wonderful. She pants as she places against you while both of you slide into the floor. <i>“I know. But I love it more because… I can use it with you, my "+ mcpronoun +"”</i> And with that, both of you fell asleep, completely spent from the use of that supernatural tail of Vivica.";
			} else {
				Board.text += "You can feel her tail teasing your cunt, soaking itself in your own fluids. <i>“One of its abilities is to transform into this…”</i> She says as it converts into a black cock, that it seems to be made from the same material that her tail is made. <i>“I’m so eager to use it with you. I’ve been practicing with me of course!”</i> You hear from her alongside a laugh as that new made-up cock is teasing your pussy. You can feel that somehow the mere touch of that is causing you to lose your mind to the pleasure. <i>“You like it rough? I do and I hope you too”</i>  You are sure that it must be linked to that strange entity energies and influences. But its rubbing its something ecstatic for you. <i>“They say that a demon tail can make someone cum just from the rub of it. It seems that it lost its full power… But that can be fixed with more uses of it, of course”</i> \n\nAfter that, she teases its tip against you, as her black pulsating cock is pressing against your insides with lustful insistence. You can see that your sister’s face is completely red, as if it were a cock connected to her. <i>“I can feel everything if that’s what you’re thinking…”</i> She says between pants, as you hug her just to feel her girly body against your "+ GameControl.mcBreast1Name.toDescription() +" chest for a second. And without further warning, she plunges her dark cock inside you, the sensation already sending you over the edge. The push of her tail is quite strong, as if someone is thrusting its hips full force against your groin every time she does it. You can help but moan wildly as she ravages your cunt with unerring skill.\n\nYou can’t last long to such demonic power, as you clamp that cock inside you with force as you orgasm hits you like a wave. Your body trembles and you can barely hold yourself on your feet as your cunt oozes all over her tail, holding her while you moan with force from the strong sensations that she is bestowing on you. You can feel your insides oozing with what seems to be some kind of gray spunk that is a bit warm to the touch. You don’t mind, as it feels even more pleasurable just like that.\n\nWhen you finally feel spent, you hold yourself from the wall behind you, telling her that her tail is wonderful. She pants as she places against you while both of you slide into the floor. <i>“Ravaging your with it is my delight, my "+ mcpronoun +"”</i> And with that, both of you fell asleep, completely spent from the use of that supernatural tail of Vivica.";
			}
		} else {
			Board.text = "You’ve been always wondering about her tail and all the capabilities of it. You’ve heard of the transformative abilities that the demons have with them and its a surprise that she is still having the same tail even when she lost the contact with the being that transformed her in the first place. So you decided to ask her, something that makes her turn towards her own ass and touch her tail. <i>“Oh, this? It has a lot of transformative capacities. But most of them are quite… special”</i> You raise one eyebrow at the word, so you ask her to show him.\n\nWhen you say that, she smiles wickedly and walks towards you as she pins you against the wall that is behind you. <i>“That can be fixed, you know?”</i> And with that, she starts undressing your clothes as her finger trails across your neck. She is quite good at undressing you, so good that you wonder if she has been training in her mind. <i>“But first, lets get you nice and easy…”</i> She says in a whisper close to your ear, as she is still floating with her magic.";
			if (GameControl.dick1Size > 0) {
				Board.text += "You can feel her tail teasing your dick, soaking itself in your own fluids. <i>“One of its abilities is to transform into this…”</i> She says as it converts into an onahole, that it seems to be made from the same material that her tail is made. <i>“And let me show you how I use it.”</i> You hear from her as that new made-up onahole is pressing against your erect "+ GameControl.mcDickType.toDescription() +" dick. You can feel that somehow the mere touch of that is causing you to lose your mind to the pleasure. You are sure that it must be linked to that strange entity energies and influences. But its rubbing and wetness is something ecstatic for you. <i>“They say that a demon tail can make someone cum just from the first rub of it. It seems to be lost its full power…”</i> \n\nAfter saying that, she teases its entrance against you, as her black warm onahole is engulfing slowly your "+ GameControl.mcDick1Name.toDescription() +" dick with lustful insistence. You can see that your sister’s face is completely red, as if it were a cock connected to her. <i>“I can feel it as if it were my own cunt…, if that’s what you’re thinking…”</i> She says between pants, as you hug her just to feel her girly body against your "+ GameControl.mcBreast1Name.toDescription() +" chest for a second. And without further warning, she plunges her dark onahole to engulf your "+ GameControl.mcDickType.toDescription() +" cock completely, the sensation already sending you over the edge. The tightness of her onahole is wonderful, as it feels as if someone is massaging your cock manually while suctioning with force over and over again. You can’t help but moan wildly as she almost forces you to ravage her tail with savagery.\n\nYou can’t last long to such demonic power, as you can’t resist to fill that onahole with your whole load as you cum hard, the pleasure coursing through you like a bolt of electricity. Your body trembles as her onahole is milking you dry more and more, your orgasm lasting more and more with every suck of it, until you can feel that you’re completely empty of spunk. \n\nWhen you finally feel spent, you hold yourself from the wall behind you, telling her that her tail is wonderful. She pants as she places against you while both of you slide into the floor. <i>“I know. But I love it more because… I can use it with you, my "+ mcpronoun +"”</i> And with that, both of you fell asleep, completely spent from the use of that supernatural tail of Vivica.";
			} else {
				Board.text += "You can feel her tail teasing your cunt, soaking itself in your own fluids. <i>“One of its abilities is to transform into this…”</i> She says as it converts into a black cock, that it seems to be made from the same material that her tail is made. <i>“And let me show you how I use it”</i> You hear from her as that new made-up cock is teasing your pussy. You can feel that somehow the mere touch of that is causing you to lose your mind to the pleasure. You are sure that it must be linked to that strange entity energies and influences. But its rubbing its something ecstatic for you. <i>“They say that a demon tail can make someone cum just from the rub of it. It seems that it lost its full power…”</i> \n\nAfter that, she teases its tip against you, as her black pulsating cock is pressing against your insides with lustful insistence. You can see that your sister’s face is completely red, as if it were a cock connected to her. <i>“I can feel everything if that’s what you’re thinking…”</i> She says between pants, as you hug her just to feel her girly body against your "+ GameControl.mcBreast1Name.toDescription() +" chest for a second. And without further warning, she plunges her dark cock inside you, the sensation already sending you over the edge. The push of her tail is quite strong, as if someone is thrusting its hips full force against your groin every time she does it. You can help but moan wildly as she ravages your cunt with unerring skill.\n\nYou can’t last long to such demonic power, as you clamp that cock inside you with force as you orgasm hits you like a wave. Your body trembles and you can barely hold yourself on your feet as your cunt oozes all over her tail, holding her while you moan with force from the strong sensations that she is bestowing on you. You can feel your insides oozing with what seems to be some kind of gray spunk that is a bit warm to the touch. You don’t mind, as it feels even more pleasurable just like that.\n\nWhen you finally feel spent, you hold yourself from the wall behind you, telling her that her tail is wonderful. She pants as she places against you while both of you slide into the floor. <i>“I know. But I love it more because… I can use it with you, my "+ mcpronoun +"”</i> And with that, both of you fell asleep, completely spent from the use of that supernatural tail of Vivica.";
			}
		}
		endTurnFun ();
	}


	void sexScene4(){
		GameControl.actualArousal = 0;

		if (NPCCharList.CharFollower [iVivica].corruptionStage >= 4) {
			Board.text = "This time, you go to Vivica’s room. You hear from her that she wanted to talk to you in a very important matter. With the way that she is, that could mean something petty or truly something life-changing. But that’s the way that she has always been and you don’t think that’s gonna end soon. When you find her in her room, you can see that she has been waiting for you patiently, contrasting the fact that she usually greets you at the first step that you take into her room.\n\nShe pats the place next to her as you sit quite confused by her behavior. <i>“"+ mcpronoun +", You know…”</i> She places one hand around your neck as she looks at you. <i>“Maybe you know that we’re somehow related and that maybe you could think that I’m too immature for this kind of thing. And I don’t blame you, but I’ve been giving this a good thought and well…”</i> You can see that she is trying to see if you can complete the phrase, so you tell her to spit it out.\n\nAnd with that, she shrugs a bit. <i>“Well, I would be honored to be the one that helps you spread your legacy. I would love to have your children, if you don’t have any problem with that”</i> You can see that she is avoiding your gaze a bit, more of worry than of shame. You are a bit surprised from her proposition but your gaze warms rather quickly, holding her face carefully and making her to look at you in your face. You tell her that you were thinking the same thing, but you thought that you would never see him as more than someone to have fun with. She smiles and almost tears from your answer, as both of you kiss passionately, not wanting to break that connection that you are having right now.\n\nBoth of you remove each other clothings until you’re both naked, trying your best not to break that bond that you’re having at that moment. <i>“That’s what I wanted to hear from you, my "+ mcpronoun +". I couldn’t be more happy… Its like a dream”</i> She says with a bright smile.";
			if (GameControl.dick1Size > 0) {
				Board.text += "Before you can say anything, she sits on the bed and spread her legs and extends her arms to you. <i>“Come to me, my dear "+ GameControl.playerName +". Don’t let the mother to-be of your child waiting”</i> And with that, you climb the bed and position yourself over her, as you rub your "+ GameControl.mcDick1Name.toDescription() +" cock against her small pussy. She kisses you once more as your cock slowly plunges into her eager cunt, sliding quickly from all the foreplay. You can’t help but moan in the middle of the kiss, as your "+ GameControl.mcDickType.toDescription() +" cock is giving her pleasure that you couldn’t think that it could be possible to give to someone like Vivica. She always seemed to be so stubborn, but she is being quite gentle with you right now.\n\nAs each of you explore the other body, as she enjoys your "+ GameControl.mcBreast1Name.toDescription() +" chest and you do in return, run your hands through her thighs, you can finally feel your own orgasm hitting you, as she moans wildly from the teasing that your cock is doing to her insides. <i>“Fill me up with your child!”</i> And with that, you can feel how your cock pulsates as your own semen starts to fill her pussy and belly, your "+ GameControl.mcDick1Name.toDescription() +" dick trembling as load after load of your spunk fills her cunt to the brim. You can feel how your are filling her with your love for her as she circles your waist with her legs and tail, as if she were scared of letting you go. She has been away from your life for so long, that you can’t blame her for feeling like that.\n\nAnd with that, both of you fell spent but sleeping together, as this is the start of something greater than any kind of creature that could try to separate both of you. As there is a connection that its now unbreakable between you two.";
			} else {
				Board.text += "Before you can say anything, you can see that she transforms her tail into a cock tip. <i>“Don’t worry. I’ve thought of everything. You only need to relax…”</i> She says as you lay on her bed, spreading your legs and presenting your wet pussy to her. She doesn’t float this time, as she climbs you until she is sitting on your belly, as her cock-tip is rubbing against your pussy. She kisses you once more as her cock slowly plungles into your eager cunt, sliding quickly from all the foreplay. You can’t help but moan in the middle of the kiss, as her black cock-tip is giving you pleasure that you couldn’t think that it could be possible from someone like Vivica. She always seemed to be so tricky, but she is being quite gentle right now.\n\nAs each of you explore the other body, as she enjoys your "+ GameControl.mcBreast1Name.toDescription() +" chest and you do in return, run your hands through her thighs, you can finally feel your own orgasm hitting you, as she moans wildly from the teasing that your cunt is doing to her tail. <i>“Get knocked up!”</i>  And with that, you can feel her own strong-scented seed starts to fill your cunt and belly, her tail trembling as load after load of her spunk fills your cunt to the brim. You can feel that hot overflowing spunk filling you with her love as you circle her waist with your legs, not letting her go. She has been away from your life for so long, but never again.\n\nAnd with that, both of you fell spent but sleeping together, as this is the start of something greater than any kind of creature that could try to separate both of you. As there is a connection that its now unbreakable between you two.";
			}
		} else {
			Board.text = "This time, you go to Vivica’s room. You hear from her that she wanted to talk to you in a very important matter. With the way that she is, that could mean something petty or truly something life-changing. But that’s the way that she has always been and you don’t think that’s gonna end soon. When you find her in her room, you can see that she has been waiting for you patiently, contrasting the fact that she usually greets you at the first step that you take into her room.\n\nShe pats the place next to her as you sit quite confused by her behavior. <i>“"+ mcpronoun +", I’ve been thinking…”</i> She places both hands over her lap as she looks into the floor. <i>“Maybe you know that we’re somehow related and that maybe you could think that I’m too immature for this kind of thing. And I don’t blame you, but i0ve been giving this a good thought and well…”</i> You can see that she is holding herself, so you place a hand on her shoulder and tell her to spit it out that she can trust you with anything she would desire.\n\nAnd with that, she closes her eyes and nods. <i>“Well, I would be honored to be the one that helps you spread your legacy. I would love to have your children, if you allow me”</i> You can see that she is avoiding your gaze. You are a bit surprised from her proposition but your gaze warms rather quickly, holding her face carefully and making her to look at you in your face. You tell her that you were thinking the same thing, but you thought that you would never see him as more than someone to have fun with. She smiles and almost tears from your answer, as both of you kiss passionately, not wanting to break that connection that you are having right now.\n\nBoth of you remove each other clothings until you’re both naked, trying your best not to break that bond that you’re having at that moment. <i>“You don’t know how long I’ve been waiting for this moment, my "+ mcpronoun +". I couldn’t be more happy…”</i> She says with a bright smile.";
			if (GameControl.dick1Size > 0) {
				Board.text += "Before you can say anything, she sits on the bed and spread her legs and extends her arms to you. <i>“Come to me, my dear "+ GameControl.playerName +". Don’t let the mother to-be of your child waiting”</i> And with that, you climb the bed and position yourself over her, as you rub your "+ GameControl.mcDick1Name.toDescription() +" cock against her small pussy. She kisses you once more as your cock slowly plunges into her eager cunt, sliding quickly from all the foreplay. You can’t help but moan in the middle of the kiss, as your "+ GameControl.mcDickType.toDescription() +" cock is giving her pleasure that you couldn’t think that it could be possible to give to someone like Vivica. She always seemed to be so stubborn, but she is being quite gentle with you right now.\n\nAs each of you explore the other body, as she enjoys your "+ GameControl.mcBreast1Name.toDescription() +" chest and you do in return, run your hands through her thighs, you can finally feel your own orgasm hitting you, as she moans wildly from the teasing that your cock is doing to her insides. <i>“Fill me up with your child!”</i> And with that, you can feel how your cock pulsates as your own semen starts to fill her pussy and belly, your "+ GameControl.mcDick1Name.toDescription() +" dick trembling as load after load of your spunk fills her cunt to the brim. You can feel how your are filling her with your love for her as she circles your waist with her legs and tail, as if she were scared of letting you go. She has been away from your life for so long, that you can’t blame her for feeling like that.\n\nAnd with that, both of you fell spent but sleeping together, as this is the start of something greater than any kind of creature that could try to separate both of you. As there is a connection that its now unbreakable between you two.";
			} else {
				Board.text += "Before you can say anything, you can see that she transforms her tail into a cock tip. <i>“Don’t worry. I’ve thought of everything. You only need to relax…”</i> She says as you lay on her bed, spreading your legs and presenting your wet pussy to her. She doesn’t float this time, as she climbs you until she is sitting on your belly, as her cock-tip is rubbing against your pussy. She kisses you once more as her cock slowly plungles into your eager cunt, sliding quickly from all the foreplay. You can’t help but moan in the middle of the kiss, as her black cock-tip is giving you pleasure that you couldn’t think that it could be possible from someone like Vivica. She always seemed to be so tricky, but she is being quite gentle right now.\n\nAs each of you explore the other body, as she enjoys your "+ GameControl.mcBreast1Name.toDescription() +" chest and you do in return, run your hands through her thighs, you can finally feel your own orgasm hitting you, as she moans wildly from the teasing that your cunt is doing to her tail. <i>“Get knocked up!”</i>  And with that, you can feel her own strong-scented seed starts to fill your cunt and belly, her tail trembling as load after load of her spunk fills your cunt to the brim. You can feel that hot overflowing spunk filling you with her love as you circle her waist with your legs, not letting her go. She has been away from your life for so long, but never again.\n\nAnd with that, both of you fell spent but sleeping together, as this is the start of something greater than any kind of creature that could try to separate both of you. As there is a connection that its now unbreakable between you two.\n";
			}
		}
		endTurnFun ();
	}



	void sexScene5(){
		GameControl.actualArousal = 0;

		if (NPCCharList.CharFollower [iVivica].corruptionStage >= 4) {
			Board.text = "Since the last time that you’ve seen your sister, you remember that you told her that she should make paces with her mother for the time being, at least being polite with her. You have seen them several times, but that doesn’t make anything set in stone, as you know how your sister is in reality, especially since she took control of that creature. Sometimes you wonder if they are just acting or if they are truly bonding just like a mother and a daughter are supposed to do. But you’re not sure how are they supposed to do, as you don’t have any good friends that are in good terms with their parents.\n\nWhile you were wandering close to her quarters, you can hear some moaning coming from your sister’s room. Its weird because you can distinguish two of them, so you can’t help but wonder if she is fucking someone else. And because of that curiosity, you take a small peek into your sister’s room but what you see, surprises you greatly. You can see that your sister is with your mother, as the latter is using her tentacles to fuck the first one against each other while enjoying a kiss of passion. And you thought that they were faking their goodwill between them. You open the door, as both of them turn to see that you arrived. Your sister eyes shine at your entrance. <i>“Oh, fuck. If I knew before that my mom would be this good, I would bonded with her a long ago! Why didn’t you told me?! She’s a beast!”</i> She says as she tries to reach for you a bit. <i>“Join us! You’re the only one that’s left from the family”</i> ";

			if (QuestControl.lucinaSlimeQueen && QuestControl.lucinaCorrupt) {
				//corrupt slime
				Board.text += "Your mother turns to see you with her usual instinctive face. She doesn’t seems to mind that you’re looking at her like that. <i>“My children together. Let’s enjoy each other”</i> She says as if its something as normal as ever, and you’re sure that its just like that for her. And you can see that her malleable body is even more endowed than the usual, as you can see that her breasts and ass are more big than before. She has been engorgin herself in the baths again? You don’t mind, but maybe knowing can make it happen more often.";
			} else if (QuestControl.lucinaSlimeQueen == false && QuestControl.lucinaCorrupt) {
				//corrupt sym
				Board.text += "Your mother turns to see you with a face full of shame. <i>“M-Master! I didn’t thought that I would… It was a request from my daughter, Master!”</i> She says, as you can see that the fact that she is almost presenting her hindquarters to you is making her even more wet than before. And you can see that her body is well-endowed as you instructed her to be, always in shape for you to use properly. As always, the symbiote leaves nothing to the imagination, but you always love to see her like that.\n";
			} else if (QuestControl.lucinaSlimeQueen == false && QuestControl.lucinaCorrupt == false) {
				//pure sym
				Board.text += "Your mother turns to see you with a red face full of lust and desire. <i>“My child! Please, come and help us. I would love to be screwed by the two of my children. Won’t you make your mother happy with that?”</i> And you can see that her body is quite desirable as always. You can’t help but see that the symbiote leaves almost nothing to the imagination, from her breasts to her wet and latex-black cunt, almost oozing for your arrival.";
			} else {
				//pure slime 
				Board.text += "Your mother turns to see you with a red face full of lust, even though her body is one of a slime, you can see that her desire for you is still there. <i>“My child! Please, come and help up. I would love to be screwed by the two of my children. Won’t you make your slime mother happy?”</i> And you can see that her body, even when its as malleable as a slime, retains her lustful appearance, probably by her own desire to be seen as that. Her tentacles are moving around Vivica, probably teasing her as much as she is teasing herself.\n";
			}


			if (GameControl.dick1Size > 0) {
				Board.text += "You don’t need to be said twice to remove your clothing and get inside the action that both of them are having without you, even thought you don’t mind that much as they are at least bonding with each other. So you start teasing them with your hands, as both of them start moaning and gasping from your touch. <i>“Don’t be late. I want you to fuck us already. I knew that we were missing something important.”</i>  You can feel Vivica’s tail and your mother Lucina’s tentacles fondling your "+ GameControl.mcDick1Name.toDescription() +" cock and teasing it with desperation until you’re rock hard for both of them. You start rubbing your cock between their cunts, as you soak it in both of their juices. Both of them start pleading to stick it in in each of them, so you oblige them. You start thrusting slowly into each of their cunts. <i>“That’s the spot! Just keep thrusting. "+ GameControl.playerName +"”</i> \n\nYou can see how both of them start thrashing their bodies, as both of them start kissing passionately while you fuck them both. Their moans and cries of pleasure are music to your ears as their extra appendages tremble around your cock as they try to guide them into their respective owner. The tight and warm pussy of your sister is wonderfully stretch for you to enjoy but the wet and malleable twat of your mother is skillful in teasing and massaging your prick with haste. Its hard to decide which one is the best, so you decide to plunder both of them. The doesn’t seem to mind about that tho, as long as you’re ramming them with your "+ GameControl.mcDickType.toDescription() +" cock.\n\nAfter groping their breasts and enjoying their cunts you can’t help but cum finally, as you can’t decide for which of them to fill you decide to give each one of them a part of it by soaking their pussies with your cum, drenching them in your white and thick spunk until you can’t do it no more. And with that, you can hear an echo of screams full of delight, as both of the ladies are having their own orgasms.\n\nWhen you’re finally spent from all that, you can tell them that its good to see how they’re bonding with each other. They can barely talk, but you can hear in your sister’s voice. <i>“We’re a family after all… I love this kind of bonding”</i> And with that, you clean yourself in their bodies and get dressed before leaving them to rest or continue their fun, whatever they want at that moment.\n";
			} else {
				Board.text += "You don’t need to be said twice to remove your clothes and get inside the action that both of them are having without you. So you start teasing them with your hands as you can feel one of the tentacles of your mother, teasing your cunt while you do so. You can feel Vivica’s hands and your mother’s groping your "+ GameControl.mcBreast1Name.toDescription() +" chest and ass while her lubricated tentacle finds its way inside your twat, as you can feel their desperation for enjoying your fleshy bits as they moan and gasp from all the weat that they were emanating. <i>“I forgive you mother! Just don’t stop ravaging us!”</i>  You start rubbing your body against their as your mother start ramming your pussy with her eager tentacle, just like she is doing with your sister.\n\nThat quickly becomes an orgy as Vivica’s tail teases your clit and you kiss your mother passionately just as Vivica was doing just before you entered. Your mother muffles her screams of pleasure on your mouth as you kiss her deeply while your sister licks your neck in a vain attempt of calming the desire that was overflowing in that room. Your mother starts enjoying your insides with even more intensity, her gooey appendage being more and more rough, your legs trembling with each time they pound your groin. The pleasure is too much for you to bear, the grinding of their lustful bodies alongside the strong rod that is fucking you at the moment is sending you over the edge quickly. <i>“Let’s cum together!”</i> \n\nAfter a couple of minutes of family-fucking, you can’t help but cum on her tentacle as your pussy trembles with the delight that its causing your mother to you, rewarding her with a steady flow of your vaginal juices, as you can feel both of them having their own orgasms, as you can feel your twat being filled with the ooze that the tentacle is spilling inside you, sending your body to the edge of delight as their collective moans fill the room in its entirety.\n\nWhen you’re finally spent from all that, you can tell them that its good to see how they’re bonding with each other. They can barely talk, but you can hear in your sister’s voice. <i>“We’re a family after all… I love this kind of bonding”</i> And with that, you clean yourself in their bodies and get dressed before leaving them to rest or continue their fun, whatever they want at that moment.";
			}
		} else {
			Board.text = "You’ve been wondering how your mother and sister are dealing with each other. You can remember that the last times that you’ve seen them, they’ve been hanging out just fine. But sometimes you wonder if they are just acting or if they are truly bonding just like a mother and a daughter are supposed to do. But you’re not sure how are they supposed to do, as you don’t have any good friends that are in good terms with their parents.\n\nBut this time, you can hear some moaning coming from your sister’s room. Its weird because you can distinguish two of them, so you can’t help but wonder if she is fucking someone else. And because of that curiosity, you take a small peek into your sister’s room but what you see, surprises you greatly. You can see that your sister is with your mother, both of them are grinding their pussies against each other while enjoying a kiss of passion. And you thought that they were faking their goodwill between them. You open the door, as both of them turn to see that you arrived. Your sister eyes shine at your entrance. <i>“Oh, my dear "+ mcpronoun +". Its a good time for… some quality time… with the family”</i> \n\n";
			if (QuestControl.lucinaSlimeQueen && QuestControl.lucinaCorrupt) {
				//corrupt slime
				Board.text += "Your mother turns to see you with her usual instinctive face. She doesn’t seems to mind that you’re looking at her like that. <i>“My children together. Let’s enjoy each other”</i> She says as if its something as normal as ever, and you’re sure that its just like that for her. And you can see that her malleable body is even more endowed than the usual, as you can see that her breasts and ass are more big than before. She has been engorgin herself in the baths again? You don’t mind, but maybe knowing can make it happen more often.";
			} else if (QuestControl.lucinaSlimeQueen == false && QuestControl.lucinaCorrupt) {
				//corrupt sym
				Board.text += "Your mother turns to see you with a face full of shame. <i>“M-Master! I didn’t thought that I would… It was a request from my daughter, Master!”</i> She says, as you can see that the fact that she is almost presenting her hindquarters to you is making her even more wet than before. And you can see that her body is well-endowed as you instructed her to be, always in shape for you to use properly. As always, the symbiote leaves nothing to the imagination, but you always love to see her like that.";
			} else if (QuestControl.lucinaSlimeQueen == false && QuestControl.lucinaCorrupt == false) {
				//pure sym
				Board.text += "Your mother turns to see you with a red face full of lust and desire. <i>“My child! Please, come and help us. I would love to be screwed by the two of my children. Won’t you make your mother happy with that?”</i> And you can see that her body is quite desirable as always. You can’t help but see that the symbiote leaves almost nothing to the imagination, from her breasts to her wet and latex-black cunt, almost oozing for your arrival.";
			} else {
				//pure slime 
				Board.text += "Your mother turns to see you with a red face full of lust, even though her body is one of a slime, you can see that her desire for you is still there. <i>“My child! Please, come and help up. I would love to be screwed by the two of my children. Won’t you make your slime mother happy?”</i> And you can see that her body, even when its as malleable as a slime, retains her lustful appearance, probably by her own desire to be seen as that. Her tentacles are moving around Vivica, probably teasing her as much as she is teasing herself.";
			}

			if (GameControl.dick1Size > 0) {
				Board.text += "\n\nYou don’t need to be said twice to remove your clothes and get inside the action that both of them are having without you. So you start teasing them with your hands, as both of them start moaning and gasping from your touch. You can feel Vivica’s tail and your mother Lucina’s tentacles fondling your "+ GameControl.mcDick1Name.toDescription() +" cock and teasing it with desperation until you’re rock hard for both of them. You start rubbing your cock between their cunts, as you soak it in both of their juices. Both of them start pleading to stick it in in each of them, so you oblige them. You start thrusting slowly into each of their cunts.\n\nYou can see how both of them start thrashing their bodies, as both of them start kissing passionately while you fuck them both. Their moans and cries of pleasure are music to your ears as their extra appendages tremble around your cock as they try to guide them into their respective owner. The tight and warm pussy of your sister is wonderfully stretch for you to enjoy but the wet and malleable twat of your mother is skillful in teasing and massaging your prick with haste. Its hard to decide which one is the best, so you decide to plunder both of them. The doesn’t seem to mind about that tho, as long as you’re ramming them with your "+ GameControl.mcDickType.toDescription() +" cock.\n\nAfter groping their breasts and enjoying their cunts you can’t help but cum finally, as you can’t decide for which of them to fill you decide to give each one of them a part of it by soaking their pussies with your cum, drenching them in your white and thick spunk until you can’t do it no more. And with that, you can hear an echo of screams full of delight, as both of the ladies are having their own orgasms.\n\nWhen you’re finally spent from all that, you can tell them that its good to see how they’re bonding with each other. They can barely talk, but you can hear in your sister’s voice. <i>“We’re a family after all… I love this kind of bonding”</i> And with that, you clean yourself in their bodies and get dressed before leaving them to rest or continue their fun, whatever they want at that moment.";
			} else {
				Board.text += "\n\nYou don’t need to be said twice to remove your clothes and get inside the action that both of them are having without you. So you start teasing them with your hands as you can feel one of the tentacles of your mother, teasing your cunt while you do so. You can feel Vivica’s hands and your mother’s groping your "+ GameControl.mcBreast1Name.toDescription() +" chest and ass while her lubricated tentacle finds its way inside your twat, as you can feel their desperation for enjoying your fleshy bits as they moan and gasp from all the weat that they were emanating. You start rubbing your body against their as your mother start ramming your pussy with her eager tentacle, just like she is doing with your sister.\n\nThat quickly becomes an orgy as Vivica’s tail teases your clit and you kiss your mother passionately just as Vivica was doing just before you entered. Your mother muffles her screams of pleasure on your mouth as you kiss her deeply while your sister licks your neck in a vain attempt of calming the desire that was overflowing in that room. Your mother starts enjoying your insides with even more intensity, her gooey appendage being more and more rough, your legs trembling with each time they pound your groin. The pleasure is too much for you to bear, the grinding of their lustful bodies alongside the strong rod that is fucking you at the moment is sending you over the edge quickly.\n\nAfter a couple of minutes of family-fucking, you can’t help but cum on her tentacle as your pussy trembles with the delight that its causing your mother to you, rewarding her with a steady flow of your vaginal juices, as you can feel both of them having their own orgasms, as you can feel your twat being filled with the ooze that the tentacle is spilling inside you, sending your body to the edge of delight as their collective moans fill the room in its entirety.\n\nWhen you’re finally spent from all that, you can tell them that its good to see how they’re bonding with each other. They can barely talk, but you can hear in your sister’s voice. <i>“We’re a family after all… I love this kind of bonding”</i> And with that, you clean yourself in their bodies and get dressed before leaving them to rest or continue their fun, whatever they want at that moment.";
			}
		}
		endTurnFun ();
	}

	void loadVivica(){
		iVivica = 0;

		while (iVivica < NPCCharList.CharFollower.Count) {
			if(NPCCharList.CharFollower [iVivica].charID == 8000){
				WorldControl.NPCID = NPCCharList.CharFollower [iVivica].charID;
				//WorldControl.PortraitID = NPCCharList.CharFollower [iVivica].charPortrait;
				WorldControl.furryPic = NPCCharList.CharFollower [iVivica].isFurry;
				WorldControl.futaPic = NPCCharList.CharFollower [iVivica].isFuta;
				break; 
			}
			iVivica++;

		}

	}

	void endTurnFun(){
		panSexPanel.sortingOrder = -500;
		PanLeftManagement.endTurnControl = true; 
		endTurnPanel.sortingOrder = 500;


	}


	// Use this for initialization
	void Start () {
		loadVivica ();

		if (GameControl.mcGender == GameControl.MCGender.MALE) {
			mcpronoun = "brother";
		} else {
			mcpronoun = "sister";
		}

	}
	
	// Update is called once per frame
	void Update () {
	
	}
}
