using UnityEngine;
using System.Collections;

public class punishmentTextPhysical {

	public static string sceneText(int selector){
		float randNum = Random.Range(0f, 100f);
		string toReturn = ""; 
		string heshe = "he", hisher = "his", himher = "him", HESHE = "He", HISHER = "His", HIMHER = "Him"; 
		if (NPCCharList.CharFollower [WorldControl.idx].charGender == NPCData.CharGender.FEMALE) {
			heshe = "she"; hisher = "her"; himher = "her"; HESHE = "She"; HISHER = "Her"; HIMHER = "Her"; 
		}

		switch (selector) {
		case 0:
			toReturn = ""+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again fails to properly to work, instead using "+hisher+" laziness to coast on by and get paid. Their superiors have mentioned this to you, and stated that they have not improved since your previous lecture to them.\n\nThat insolent bastard! You have "+ NPCCharList.CharFollower [WorldControl.idx].charName +" brought to you immediately and have "+himher+" stand forth of you within your grand hall. You approach "+himher+" against the guard’s advice, and before anyone can say anything else, you slap "+ NPCCharList.CharFollower [WorldControl.idx].charName +" as hard as you’ve ever slapped someone before, the force knocking "+himher+" down to the ground.\n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +"’s lip begins to bleed, apparently "+heshe+" bit down on "+hisher+" inner cheek upon impact, and hitting the floor split "+hisher+" lip. As your subject struggles to get up, you pace around them, mentioning failures committed and how these can eventually lead to bigger problems for you, themselves, and everyone that works with "+himher+" down the road. As "+ NPCCharList.CharFollower [WorldControl.idx].charName +" gets up, you look "+himher+" in the eye and make sure that "+heshe+" understands exactly what you are saying. You receive a nod, and signal "+himher+" to leave the hall. You are finished with "+himher+" for now.";
			return toReturn;
		case 1:
			toReturn = ""+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again has begun to slack off within "+hisher+" field of work and it has begun to become a problem amongst many other workers. You realize it is a problem when "+ NPCCharList.CharFollower [WorldControl.idx].charName +" continues to be unproductive and brushes off the threats of "+hisher+" supervisors, causing you to intervene and bestow some ruling and punishment of your own.\n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +" is brought to your grand hall, cuffed at the wrist and ankles. Your guards already know what kinds of punishments you have in mind for this hopeless fool, and begin to prepare "+himher+" before you are ready to discuss business with them.\n\nThe guards have stripped "+ NPCCharList.CharFollower [WorldControl.idx].charName +" of their upper wear, and have prepared several candles to use for the session. As "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is restrained, you take your candle stick and gently try to balance the candle before you start pouring boiling hot wax on the neck, chest, and back of "+ NPCCharList.CharFollower [WorldControl.idx].charName +". The pain is not kinky this time, the wax truly is burning into their skin, blistering the delicate flesh. "+ NPCCharList.CharFollower [WorldControl.idx].charName +" begins to scream as you violently peel off the mask off of "+himher+", causing burns to open up and bleed. \n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +" eventually blacks out from the pain on the 3rd candle, and is dragged to the infirmary once again. You hope that this isn’t the last time you use candles for torture, you apparently have a talent for it.";
			return toReturn;
		case 2:
			toReturn = ""+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again has begun to slack off within "+hisher+" field of work and it has begun to become a problem amongst many other workers. You realize it is a problem when "+ NPCCharList.CharFollower [WorldControl.idx].charName +" continues to be unproductive and brushes off the threats of "+hisher+" supervisors, causing you to intervene and bestow some ruling and punishment of your own.\n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +" is brought to your grand hall, cuffed at the wrist and ankles. Your guards already know what kinds of punishments you have in mind for this hopeless fool, and begin to prepare "+himher+" before you are ready to discuss business with them.\n\nWhen you arrive in your hall, "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is forced down, with their rear in the air. You mention to "+himher+" how their recent actions have been rather naughty and that naughtiness needs to be punished. With the snap of your fingers, one of your guards pulls down the trousers of "+ NPCCharList.CharFollower [WorldControl.idx].charName +", exposing "+hisher+" supple, round, almost pale behind. You take a good look at "+hisher+" crotch out of curiosity before you move onto the main punishment.\n\nPutting your rings on and flexing your hand, you begin to slowly, violently spank "+ NPCCharList.CharFollower [WorldControl.idx].charName +". "+ NPCCharList.CharFollower [WorldControl.idx].charName +" does "+hisher+" best at concealing their screams, but after the 4th or 5th blow, sound begins to escape from "+hisher+" mouth. You stop after the 10th slap, their ass black, blue, and pink, throbbing at the violent blows you have given them.\n\nYou tell "+ NPCCharList.CharFollower [WorldControl.idx].charName +" that you hope "+heshe+" has learned a lesson and then let them go, hopefully for the last time.";
			return toReturn;
		case 3:
			toReturn = "WIP";
			return toReturn;
		case 4:
			toReturn = ""+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again has begun to slack off within "+hisher+" field of work and it has begun to become a problem amongst many other workers. You realize it is a problem when "+ NPCCharList.CharFollower [WorldControl.idx].charName +" continues to be unproductive and brushes off the threats of "+hisher+" supervisors, causing you to intervene and bestow some ruling and punishment of your own.\n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +" is brought to your grand hall, cuffed at the wrist and ankles. Your guards already know what kinds of punishments you have in mind for this hopeless fool, and begin to prepare "+himher+" before you are ready to discuss business with them.\n\nFoolish "+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again needs to be dealt with, and spankings are not enough this time. One of your advisors suggests a flogging whip, to which you happily agree upon. As you arrive to your hall, "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is restrained on "+hisher+" knees. When you are ready, you snap your fingers and one of your guards lifts the back of "+ NPCCharList.CharFollower [WorldControl.idx].charName +"’s garb, exposing "+hisher+" bare back. Whip in hand, you begin to flog "+ NPCCharList.CharFollower [WorldControl.idx].charName +" with speed and precision, making sure to hit all major parts of the back, including the sides and the shoulders.\n\nAfter a few blows, "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is biting their lip and sobbing softly, "+hisher+" tears flowing as freely as the blood oozing from the lash wounds. A few more licks and you realize that you might have gotten too far, as the carpet and your wardrobe both are stained with the blood of this fool.\n\nYou have the guards take "+ NPCCharList.CharFollower [WorldControl.idx].charName +" to the infirmary for minimal first aid as you retire to your quarters.";
			return toReturn;
		case 5:
			toReturn = "WIP";
			return toReturn;
		case 6:
			toReturn = ""+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again has begun to slack off within "+hisher+" field of work and it has begun to become a problem amongst many other workers. You realize it is a problem when "+ NPCCharList.CharFollower [WorldControl.idx].charName +" continues to be unproductive and brushes off the threats of "+hisher+" supervisors, causing you to intervene and bestow some ruling and punishment of your own.\n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +" is brought to your grand hall, cuffed at the wrist and ankles. Your guards already know what kinds of punishments you have in mind for this hopeless fool, and begin to prepare "+himher+" before you are ready to discuss business with them.\n\nAs you arrive, you are ready to punish "+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again. This time you have brought a riding crop. Heshe is chained down, with "+hisher+" pants down. You gently sit upon them as you begin to flog their ass raw, as you “ride” upon "+hisher+" back. Each blow makes "+ NPCCharList.CharFollower [WorldControl.idx].charName +" tense up, but that does not slow you down.\n\nEventually you must stop. Blood is flowing down "+hisher+" thighs freely, staining the carpet once more. The guards drag "+himher+" to the infirmary for minor first aid as you leave to your quarters.";
			return toReturn;
		case 7:
			toReturn = ""+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again has begun to slack off within "+hisher+" field of work and it has begun to become a problem amongst many other workers. You realize it is a problem when "+ NPCCharList.CharFollower [WorldControl.idx].charName +" continues to be unproductive and brushes off the threats of "+hisher+" supervisors, causing you to intervene and bestow some ruling and punishment of your own.\n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +" is brought to your dungeon and is prepped for punishment by the denizens that work within the underground of your rule. Stripped naked, "+heshe+" is tied up and held upside down via pulley system. Your men greet you as you arrive, as you formally declare to "+ NPCCharList.CharFollower [WorldControl.idx].charName +" of the crimes and failures committed against you. Before any complaints or excuses can follow, you begin the torture.\n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +" is lowered head first into a barrel filled with water. Every so often you let "+himher+" come up for air just for a brief second, and sometimes you splash the fool in the face to trigger a scare or two. This goes on for hours, sometimes you remain to watch, sometimes you wander off and return to see if the torture has changed anything.\n\n6 hours later, "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is freed upon your word, barely maintaining sanity, and truly fearing your word. Hopefully you do not have to torture "+himher+" again, for the next punishment might be lethal…";
			return toReturn;
		case 8:
			toReturn = ""+ NPCCharList.CharFollower [WorldControl.idx].charName +" continues to be unproductive and slow within their field of work. You call "+himher+" to your hall once again. Once they arrive you have one of your strongest guards disarm themselves before approaching "+ NPCCharList.CharFollower [WorldControl.idx].charName +". With a nod to the guard, "+ NPCCharList.CharFollower [WorldControl.idx].charName +" begins to be beaten by your guard, whilst being held back by other warriors in your hall.\n\nYou don’t lecture "+ NPCCharList.CharFollower [WorldControl.idx].charName +", all you simply say is that they should know why they are being beaten right now. You sip wine as you watch "+ NPCCharList.CharFollower [WorldControl.idx].charName +" take a few more blows to the stomach before you. One more solid hit and "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is vomiting on the ground. You tell the guard to ease up before telling "+himher+" to leave this place at once. However, "+heshe+" is unable to stand up. You need your guard to ultimately drag "+himher+" out of your hall, and toss "+himher+" onto the steps till they have recovered.\n\nWhile "+ NPCCharList.CharFollower [WorldControl.idx].charName +" continues to disappoint you, your punishments for "+himher+" have begun to interest you greatly.";
			return toReturn;
		case 9:
			toReturn = "This is it. "+ NPCCharList.CharFollower [WorldControl.idx].charName +" has failed you and everyone around "+himher+" one too many times. After much deliberation, you realize that all other types of punishments have not been sufficient, and there are no other options. "+ NPCCharList.CharFollower [WorldControl.idx].charName +" once again is captured by your guard and has been taken down to your dungeon, and is stripped nude.\n\nYou arrive and begin to confront "+himher+" about their failures as a worker, and that this is the last punishment you can give them before you have to publicly execute them, or sell them into slavery into another kingdom. "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is presented with your custom made Iron Maiden. This device however is not meant to kill, just maim and damage the subjects within, using dulled, shortened spikes.\n\n"+ NPCCharList.CharFollower [WorldControl.idx].charName +" begins to beg, but you have already handed out too many chances up to this point. Your men force "+ NPCCharList.CharFollower [WorldControl.idx].charName +" into the contraption and lock it shut, as their screams are muffled within the device. You go to your guard, and tell them that this is for a whole day.\n\n24 hours pass. "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is freed, as "+heshe+" collapses onto the dirty, cold ground, covered in shallow wounds, bruises and their own filth. After this, there is no way "+heshe+" could defy you or others in general. "+ NPCCharList.CharFollower [WorldControl.idx].charName +" is showered off and sent to the infirmary afterwards, a shell of a person "+heshe+" used to be.\n\nHopefully that is the last time you have to seriously punish someone.";
			return toReturn;
		default:
			/*if (randNum > 66) {
				toReturn += "\n\n";
			} else if (randNum > 33) {
				toReturn += "\n\n";
			} else {
				toReturn += "\n\n";
			}*/
			return "";
		}

	}




}
