using UnityEngine;
using System.Collections;

public class CombatSexSceneVictoryGeneric  {


	// oral
	public static string GenericSexOral(){
		string heshe = "he", hisher = "his", himher = "him", HESHE = "He", HISHER = "His", HIMHER = "Him"; 
		if (NPCCharList.CharMonster [0].charGender == NPCData.CharGender.FEMALE) {
			heshe = "she"; hisher = "her"; himher = "her"; HESHE = "She"; HISHER = "Her"; HIMHER = "Her"; 
		}

		if (GameControl.dick1Size > 0) {
			return ""+ NPCCharList.CharMonster [0].charName +" is lying down in the ground, defeated and looking at you with ire in"+ hisher +"eyes. You walk towards "+ himher +" and "+ heshe +" tries to escape, but you block"+ hisher +"way and order "+ himher +" to stay put.\n\n"+ HESHE +" gives up, knowing that"+ hisher +"fate is in your hands, and is not like these things aren’t already common place in the wild. \n\nYou quickly slip your way out of the clothing between your prick and"+ hisher +"face, before rubbing your floppy cock against"+ hisher +"face. "+ HESHE +" huffs, nose wrinkling before "+ heshe +" finally fives in, letting you slip your member in.\n\nIt takes you a minute to get hard due to"+ hisher +"lack of enthusiasm, but once you are certain that "+ heshe +" isn’t going to catch you off-guard with a wicked bute, you grow more eager. Once your cock is finally at full mast, the mood of the beast also shifts. Soon enough"+ hisher +"tongue starts to please you, and"+ hisher +"throat grows more accommodating.\n\n"+ HESHE +" gets on"+ hisher +"knees in order to serve you better, and to your delight "+ heshe +" begins masturbating too, syncing the pace of"+ hisher +"hand with"+ hisher +"eager mouth. \n\nPlayful, the creature clearly has"+ hisher +"fair share of experience using their mouth, and apparently knows how to take care of a cock."+ hisher +"tongue plays across all of your weakspots while"+ hisher +"throat tightens up around the head of your member.\n\nWhether "+ heshe +" is used to being defeated and has to do this a lot, or just loves dick, it doesn’t takes long for "+ himher +" to make you cum, unloading all of your seed. "+ heshe +" swishes your load around before slowly swallowing, looking up at you.\n\nNow that "+ heshe +" is done, what would you like to do with "+ himher +"? ";
		} else {
			return ""+ NPCCharList.CharMonster [0].charName +" is lying down in the ground, defeated and looking at you with ire in"+ hisher +"eyes. You walk towards "+ himher +" and "+ heshe +" tries to escape, but you block"+ hisher +"way and order "+ himher +" to stay put.\n\n"+ HESHE +" gives up, knowing that"+ hisher +"fate is in your hands, and is not like these things aren’t already common place in the wild. \n\nYou tug away the bottom portion of your clothing and flick your underwear aside before dropping down onto"+ hisher +"face. "+ HESHE +" lets out a grumble of complaint before finally opening"+ hisher +"mouth. "+ HISHER +" tongue presses against your sopping box with a tiny grunt.\n\nIt takes you a minute to get hard due to"+ hisher +"lack of enthusiasm, but once you are certain that "+ heshe +" isn’t going to throw you off of "+ himher +", you grow more eager. Once your womanhood is finally soaking properly, the mood of the beast also shifts. Soon enough"+ hisher +"tongue starts to please you, and"+ hisher +"hands join in on the action.\n\nPlayful, the creature clearly had "+ hisher +" fair share of experience using "+ hisher +" mouth, and really knows how to take care of a pussy, using "+ hisher +" tongue along all of your weak spots. \n\n"+ HESHE +" masturbates too, syncing"+ hisher +"hands to the ministrations of"+ hisher +"tongue. The pleasure is too much for you, making your legs weak, and shortly after you have a strong orgasm. You drench"+ hisher +"face with feminine cum while "+ heshe +" explodes at the same time.\n\nAlthough you are finished "+ heshe +" remains knelt, busily cleaning your body of fluids before sitting calmly on the floor, awaiting"+ hisher +"fate.\n\nNow that your ordeal is complete, what would you like to do with "+ himher +"? \n";
		}
	}

	//ride (use the npc penis)
	public static string GenericSexRide(){
		string heshe = "he", hisher = "his", himher = "him", HESHE = "He", HISHER = "His", HIMHER = "Him"; 
		if (NPCCharList.CharMonster [0].charGender == NPCData.CharGender.FEMALE) {
			heshe = "she"; hisher = "her"; himher = "her"; HESHE = "She"; HISHER = "Her"; HIMHER = "Her"; 
		}

		string A0 = "pussy";
		if (GameControl.dick1Size > 0) {
			A0 = "asshole";
		}
		return ""+ NPCCharList.CharMonster [0].charName +" tries to run away but stumbles, ending up in the dirt. "+ HESHE +" keeps trying to scramble away until you put your feet up on top of "+ himher +" with a smile.\n\n"+ HESHE +" looks at you, defiant at first. After a few heartbeats  "+ heshe +"  sighs and readies "+ himher +"self for what comes next for a loser in the wild.\n\nAlthough you could do many things, you noticed during your battle that  "+ heshe +"  is packing a sizable bulge. You undress yourself and sit on top of "+ himher +", grinding your ass against"+ hisher +"slowly-hardening dick. You trail your fingers across"+ hisher +"chest and face, grinning wickedly.\n\nOnce "+ heshe +" is sure you don’t intend to hurt "+ himher +" any further, they get more comfortable. A few jerks of their hips have their cock rubbing between the ass of your cheeks.\n\nNow that "+ heshe +" is ready, you take"+ hisher +"cock and push it up against the entrance of your "+A0+", teasing "+ himher +" until your entrance is well lubricated with pre. \n\n"+ HISHER +" hips start to rise, pushing up insistently while"+ hisher +"eyes beg you to let"+ hisher +"prick inside. You let the moment drag out longer before you finally drop your hips down hard enough to set your ass cheeks to quivering, engulfing"+ hisher +"cock with your hot innards.\n\nYou can feel how your body adapts to the size and shape of"+ hisher +"cock, feeling pleasure with each thrust "+ heshe +" drives into you. \n\nThe furious beast that faced you minutes ago is no more, and what’s left is a lustful creature in dire need of release, fucking you wildly to fulfill"+ hisher +"instinct. \n\nThe sound of your fucking is so loud there’s a fear you may attract someone else to the scene… of course, you’ve got something more important on your mind; hard animalistic fucking.\n\nYou lose track of how much time passes, but when your climax finally arrives you arch your back and let yourself go so hard that you’re sure everyone within a mile could have heard you.\n\nSatisfied you stand up, freely leaking fresh hot monstrous jizz. The beast is napping, exhausted from both your hard-fought battle, and your hard-fought fucking. Now you just have to decide what to do with "+ himher +".";

	}

	// mc fuck 
	public static string GenericSexFuckNPC(){
		string heshe = "he", hisher = "his", himher = "him", HESHE = "He", HISHER = "His", HIMHER = "Him"; 
		if (NPCCharList.CharMonster [0].charGender == NPCData.CharGender.FEMALE) {
			heshe = "she"; hisher = "her"; himher = "her"; HESHE = "She"; HISHER = "Her"; HIMHER = "Her"; 
		}

		if (GameControl.dick1Size > 0) {
			return ""+ NPCCharList.CharMonster [0].charName +" tries to run away but stumbles, ending up in the dirt. "+ HESHE +" keeps trying to scramble away until you put your feet up on top of "+ himher +" with a smile.\n\n"+ HESHE +" is startled when you get up and roughly grab "+ himher +" by the hips, exposing "+ hisher +" butthole to the air. Too exhausted to fight back and knowing that this is pretty much the law in the wild, "+ heshe +" sighs and readies "+ himher +"self for what comes next for a loser in the wild… although  "+ heshe +"  is hardly cooperative. \n\nYou suck two of your fingers and push them deep inside "+ hisher +" backdoor; "+ HESHE +" clenches tightly around your intruding digits. Moments later  "+ heshe +"  raises "+ hisher +" butt into the air, granting you better access.\n\nWith the two of you in the mood already, you give "+ himher +" a loud spank and take your cock out, which you rub and push against "+ hisher +" ring until your pre has done it’s job of lubricating it.\n\nSoaking in the moment for a few heartbeats further, you finally slam your hips home hard enough to press "+ himher +" into the ground. "+ hisher +" pleasure isn’t even a concern for you, but judging by the gasps and grunts beneath you,  "+ heshe +"  is enjoying "+ himher +"self. \n\nIt doesn’t take long until you’re riding the edge of orgasm and  "+ heshe +"  knows it, begging you for your cum just moments before your release. \n\nYou pull "+ himher +" as hard into your body as you can, driving yourself balls deep, flooding "+ hisher +" innards with your seed while  "+ heshe +"  climaxes too, arching "+ hisher +" back before they fall to the mud again, passing out. \n\nAfter dressing yourself once more the beast is at your mercy, what should you do with "+ himher +"? ";
		} else {
			return ""+ NPCCharList.CharMonster [0].charName +" tries to run away but stumbles, ending up in the dirt. "+ HESHE +" keeps trying to scramble away until you put your feet up on top of "+ himher +" with a smile.\n\n"+ HESHE +" is startled when you get up and roughly grab "+ himher +" by the hips, exposing "+ hisher +" pussy to the air. Too exhausted to fight back and knowing that this is pretty much the law in the wild, "+ heshe +" sighs and readies "+ himher +"self for what comes next for a loser in the wild… although  "+ heshe +"  is hardly cooperative. \n\nYou suck two of your fingers and push them deep inside "+ hisher +" cunt; "+ HESHE +" clenches tightly around your intruding digits. Moments later  "+ heshe +"  raises "+ hisher +" butt into the air, granting you better access.\n\nWith the two of you in the mood already, you give "+ himher +" a loud spank and take your cock out, which you rub and push against "+ hisher +" twat until your pre has done it’s job of lubricating it.\n\nSoaking in the moment for a few heartbeats further, you finally slam your hips home hard enough to press "+ himher +" into the ground. "+ hisher +" pleasure isn’t even a concern for you, but judging by the gasps and grunts beneath you,  "+ heshe +"  is enjoying "+ himher +"self. \n\nIt doesn’t take long until you’re riding the edge of orgasm and  "+ heshe +"  knows it, begging you for your cum just moments before your release. \n\nYou pull "+ himher +" as hard into your body as you can, driving yourself balls deep, flooding "+ hisher +" innards with your seed while  "+ heshe +"  climaxes too, arching "+ hisher +" back before they fall to the mud again, passing out. \n\nAfter dressing yourself once more the beast is at your mercy, what should you do with "+ himher +"? ";
		}

	}

}
