using UnityEngine;
using UnityEngine.UI;
using System.Collections;

public class AurorumScene : MonoBehaviour {

	public Text Board; 




	void DowntownStart (){
		if (CityControl.city100DowntownMeet == false) {
			Board.text = "You visit the streets of the city for the first time. The place is not so cozy, though ... No wonder nobody in the citadel wanted to get so far to a place like this, the place is neglected, and most buildings are ruined beyond repair. Nonetheless, people is curious about your presence, and you can see in their eyes that they have hope that you bring change... And at this point, any change will do. "; 
			CityControl.city100DowntownMeet = true; 
		}
		else if (CityControl.city100Prosperity < 50) 
		{
			if (CityControl.city100Corruption >= 100) {
				Board.text = "Looking around, it is almost impossible to find a single person who isn’t infected, the city has really become a hub of debauchery and perversion. The streets became a place for both creative expression and pleasure: Musicians, soldiers, merchants or mothers, everyone was involved with the community, and it was hard to find a place free from the sounds of moans and lewd acts. Most of the unoccupied buildings now are being used as cheap places to indulge their desires. Some people are covered in mud and sweat but they didn't seem to mind at all. The prostitutes became a larger working force on the city, working together with the brothel of the city.\n\nThe spirits of the inhabitants are quite high, now that its sense of morality has been revolutionized, enjoying their life without fears or judgment. The few uninfected that still lived in the city had to hide from the infected, who now are the clear majority. The city is a hole of lasciviousness and desire, every urge sated at the spot. The clothing is almost optional, but when is donned its bright and colorful or plainly obscene. The streets are filled with laughter and joy from its citizens. Almost everyone have a transformation now, be it visible or hidden. The scent of sexual fluids, cheap alcohol and diluted perfume fills the air around you. Slavery exists only as part of these acts, since no one really cares about law and order anymore, and no one would try to enforce a claim of property in anyone else.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 80) {
				Board.text = "The mood of the city, although it is almost in ruins, is exciting and full of energy. The streets were busy with people moving from one side to the other, and public orgies could be found anywhere. Drugs, rape, and all kind of crimes where part of the daily routine, but more often than not the guards were also part of that. The buildings are still in a desperate need of repairs, but the people decided to paint the cracks and create its own bizarre style with them. The people are dusty but they didn't seem to care about it at all, even some of them added the dust as part of their clothing style. The prostitutes became a bigger group on the street than before, along with some risky acrobats and comedians on the streets.\n\nThe spirits of the inhabitants are high, having a twisted morality compared from what they once had.. The infected have almost taken most of the power, creating almost a new city from the one it was before. The city has been freed from the chastity of the Empire, and instead is dominated by a sense of freedom that no one in the city experienced before. The people are hectic, enjoying the carnal pleasures with enthusiasm. The people are now what they want to be, be it good or bad. The uninfected are treated with spite due to the grudges of the infected against them, and most of them now live in isolated ghettos. The clothing of the citizens are now more extravagant or revealing. The transformed people are now the important people among the townsfolk, as more and more people come into them to be transformed. Now most of the slaves are people who submit themselves as such, looking to fulfill their own perversions in exchange of their freedom. \n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 60) {
				Board.text = "Although the city is almost in ruins, and people lacks luxury, there is a weird sense of peace, freedom and maybe even happiness. The streets are lively, full of people that most of the time are engaging in sex and soft drugs. The streets were full of bizarre graffitis or paintings, giving them a completely different look. The buildings style has changed, now being more diverse and ebullient, as they are being lightly repaired and repainted, but still were far from restored. You found out that now there were a couple of scantily clad prostitutes where the beggars used to be, and half the time doesn’t seem that they even need a room to work.\n\nThe spirits of the inhabitants are good, yet somehow twisted from the normality they once had. The infected have surpassed the uninfected, and so the city has taken a new direction. The city now is more free from the moral shackles it once had. Now the people dresses in more scandalous ways, showing more skin than before. Some of the most prominent people in the city had become infected themselves, and now there is an aggressive attitude towards the uninfected, although the approach is more seductive than violent. Slavery as an institution is becoming weak in comparison when the city was more prude, and is more reserved for those who commit grave crimes instead of just being infected. It's tone has become more sexual than productive, and their treatment in general has improved. Actually, most of slaves seem to be somewhat happy with their situation, probably thanks to the indulgence of their masters that satisfy them.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 40) {
				Board.text = "The city is in an uproar, which only escalates the state of disarray of the city. The infected became more public, as their numbers grew, trying to act as normal citizens with mixed results.A good amount of the buildings started to get repaired by the Infected, creating new and distinct styles of architecture that contrasted with the sober style of the regular citizens.. The beggars have almost disappeared, as most of them joined a gang or hid wherever they can.\n\nThe spirits of the inhabitants are gloomy, completely in tune with the condition of the city they are living in. The people were divided between the ones that were not infected, and the infected themselves, both sides fighting for dominance of the city and sometimes resorting to violence. The citizens gathered in groups to keep themselves safe from the infected, or vice versa. It is common now to see people give themselves freely to their urges, anywhere and at anytime, and the guards are unable to respond to these “petty crimes”. The transformed people don’t hide that much anymore, and instead try to persuade people to submit at them, with more success than the citizenry would like to accept. Although slavery is on the rise, its tone has changed lately, used less for labor and more for pleasure or a symbol of status. \n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 20) {
				Board.text = "The condition of the city is very chaotic, almost in perpetual conflict between the infected and the population. The alleys are getting more and more populated with infected. The buildings were still in pretty bad shape, but now most of the empty buildings are now being used as a refugee for a large group of infected people, both good and bad. It’s hard for the people to wash themselves properly, due to fear of being infected from the large population of people carrying the plague roaming the streets. The beggars are now a small group of people that are transformed but is too sick or lame to hide properly.\n\nThe spirits of the inhabitants are agitated, in tune with the condition of the city they are living in. The regular citizens were in a constant state of caution, as the population of infected kept growing. The people prefer to gather in their homes or private spaces, keeping themselves away from the immoral decadence that paves the roads around them. The infected are becoming more daring, indulging in their vice at any hour of the day, although there are still some safe spaces for the citizenry. The transformed people walk with precaution, since the guards have their hands full already with so much crime and chaos, and violence is part of everyday's life. You notice that the slave population is significant, but it is coming to the point that it is difficult to regulate\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 0) {
				Board.text = "The city is in shambles, yet there is more activity flourishing in the streets. The streets are barely holding themselves, and with no more than a handful of guards patrolling them, a group of subversives started to hide among the back alleys. The buildings are in a bad shape, they can continue working due to a great deal of effort from their workers. Most of them were abandoned, so some infected used them for a place to hide from the common eye. The people are dusty and some of them fight illnesses due to the decadence of the city. The beggars started to dwindle, as some of them got infected and started to hide along with the others affected by the plague.\n\nThe spirits of the inhabitants are good, regardless of the condition of the city they are living. There is an aura of camaraderie among the people, but there are some dissidents among them, wreaking havoc from time to time. The people gather in the parks of the city, trying to keep themselves safe from the dangers that roamed the community. Some of them are infected, and while some of them indulge in their new cravings, the city keeps a good level of moderation in their urges. The people that has been transformed walk cautiously, the people around them usually being civil enough to treat them fairly, but sparks of violence among infected and the population were not unheard of. You notice that most of the population of slaves is growing: the plague and corruption is forcing the hand of the city.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			}else if (CityControl.city100Corruption <= 0) {
				Board.text = "The population is doing what they can with what they have, but the city is almost in ruins. The businesses are barely holding themselves, surrounded with gravel that the people try to clean as much as possible, although that’s not enough as they keep crumbling from time to time. The buildings are in a deteriorated state, most of them requiring repairs, but the citizens do their best to continue operations. The people are dusty and some of them fight illnesses due to the decadence of the city. The beggars are a large portion of the people on the streets, since the city lacks the infrastructure to provide jobs.\n\nThe spirits of the inhabitants are quite high, regardless of the condition of the city they are living. Most of them are friendly with their fellow citizens. Despite the temple on the city being left neglected, the people attends to it, trying to gather the people and thank for the tranquility of the city. Many of them are infected, but they keep their urges at bay, with the support of the people around them. The transformed people walk through the streets without the fear of violence, but some humans still keep their distance from them fearing the plague, although the city is doing successful efforts to reconcile the community. You notice that most of the people are freemen: tackling the problem of the plague has reduced the need of slaves for labor.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} 

		} 
		else if (CityControl.city100Prosperity >= 50) 
		{
			if (CityControl.city100Corruption >= 100) {
				Board.text = "The city improved into something completely different from the city you inherited at the start of your journey. Almost every building in your city has been twisted into something suggestive or chaotic. The businesses remain open until past the early morning, and the people move from one to the other until they close. \n\nThe spirits of the inhabitants are quite high, now that its morality is completely twisted, its past one almost vanished from their memory. The uninfected are almost out of sight, gathering themselves in small neighborhoods. The city is a hole of concupiscence and lust, every whim had a place to be sated. The clothing is almost optional, but when is donned its bright and colorful thanks to the newly imported clothing, or skimpy enough to be barely considered clothing, and when not donned is with humiliating or lewd tattoos across their bodies. The streets are filled with laughter and joy from its citizens. Almost everyone has a transformation now, heavily combined with clothings that accentuate them. The scent of sexual fluids, alcohol and strong perfume fills the air around you.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 80) {
				Board.text = "As you recount the changes in the last weeks, you’re sure that the city barely resembles the city you inherited at first. Not only the buildings look more vivid than before, but also the city is full of life, the screams of lust and delightment echoing through the city. The people were more direct with their desires, as the dances were definitively erotic or their interactions were sexual in nature.  \n\nThe spirits of the inhabitants are high, as its twisted morality helps them to enjoy the small improvements of the city with more enthusiasm. The infected have almost taken most of the city, creating almost a new culture from the one it was before. The city has been freed from the chastity of the Empire and returned to its old wicked ways. The gathering groups where the people sate their carnal desires were becoming more and more popular. The people are now what they want to be, be it good or bad. The clothing of the citizens are now more extravagant or revealing. Some of these clothing were plainly erotic, but some other were intricate and outstanding.  The transformed people are now the owners of these business, thriving in the lust for new sensations of the public.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 60) {
				Board.text = "As you think of the actual state of the city, you see that it has changed as it improved the quality of life of their population. The important buildings on the city got repainted with more vivid colors and covered in large fabrics, giving them a more informal appearance. The clothing of the people was more elaborated than before, even when they were being lewd. The fabrics they used were of decent quality, meaning that the economy has returned at least for a bit. The nightlife of the city was getting more and more prominent, the music could be barely heard up your manor at night.\n\nThe newly twisted spirits of the inhabitants are good, especially since the city has been prospering in the past weeks. The infected have surpassed the uninfected, and so the city has taken a new direction. The city now is more free from the moral shackles it once had, imposed by the Citadel. Now the people dresses in more scandalous ways, showing more skin than before. New small business have appeared, catering to lewd kinks or interesting shows for the public. The transformed people are now prominent people in the city, now publicly trying to call to the uninfected to join their chaotic way of living.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 40) {
				Board.text = "The city was still healing from the lasting effects of the plague, but you heard that something was happening on the streets.. A good amount of the buildings were getting a lot of repairs, most of the forgotten buildings were restored and ready for use. The clothing of the citizens ranged from plain clothing to brightly colored full-dresses. The buildings of the infected stand out a lot when you compared them to the regular ones of the uninfected.\n\nThe spirits of the inhabitants are abject, but at least they feel an improvement. The people were divided between the ones that were not infected, and the infected themselves, both sides fighting for dominance of the city, but the guard defusing any major conflict before it escalates. The citizens gathered in groups to keep themselves safe from the infected, or vice versa. Some of the citizens are infected, and now some of them started creating underground groups to sate their new desires. The transformed people that are also infected are being more and more scandalous, trying to allure those that are not infected by the Plague into those groups.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 20 ) {
				Board.text = "The city is getting more and more active as the city is recovering from its dark times after the plague. The roads are getting more and more full of infected people that tried to get a place among the citizens, despite the cries of the latter to be expelled from the city. They pay for small, secluded places at the edge of the city. Their revealing clothing and bizarre sense of fashion wasn’t that different from what is already trending in the city. The city started to have a small night life on its own, as some buildings started to extend their closing time.\n\nThe spirits of the inhabitants is improving, although still considerably low. The non-infected people are in a constant state of caution, trusting the guards to keep the things as stable as they can. The population isolates themselves in their homes or private places, to avoid the immorality that roams the streets of the city.  The transformed people walk with precaution, since in these times of turmoil violence is now part of everyday's life. You notice that the slave population is significant, but it is coming to the point that it is difficult to regulate.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption > 0) {
				Board.text = "As the city prospers, the activity is slowly returning to the streets.The streets were transitable once more, yet some activity is still being seen through the corridors and alleys of the city. Some of the most prominent buildings were repaired, but the new decoration was more phallic than it needed to be. The people now can afford proper clothing, although some decided to dress in outlandish forms. As the beggars started disappearing, drunk people takes its place in the streets, now that they had an income to spend on their vices. At least the economy was moving.\n\nThe spirits of the inhabitants are good, especially since their conditions are improving. There are some dissidents, but they endanger the little progress the city is having, so they are being frowned upon. The people gather close to the guards of the city, now that they are forming real units, rather than a pair of soldiers in specific locations. A small segment of the population is infected, and while some of them indulge in their new cravings, the city keeps a good level of moderation in their urges. The people that has been transformed walk cautiously, the people around them usually being civil enough to treat them fairly, but sparks of violence among infected and the population were not unheard of. You notice that slavery is on the rise, in order to control the recent growth of both population and infected people, and most of them are put in good use as forced labor. \n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} else if (CityControl.city100Corruption <= 0) {
				Board.text = "The city is being repaired slowly, but it's still far from the glory it once had. The roads are now delimited with rocks and cleaned up, clear from trash and filth. The important buildings are now in a better state than before, most of them got painted to be recognized from the others, to see the improvement of the city. The people in it now can afford a proper set of clothing and seems that the diseases start to recede due to the improvement in general of the city. There are only few beggars on the streets, as the prosperity of the city reignited the fire of commerce once again\n\nThe spirits of the inhabitants are quite high, especially now that their conditions are improving. Most of them are friendly with their fellow citizens. Now that the parks and entertainment places are being taken care of, more people attends to them, trying to get a respite from their past difficulties. The ones who are infected keep their urges at bay, with the support of the people around them. Now that there were places for the people to relax, the transformed people stopped being the center of attention, and the city is providing the funds and it’s efforts to reconcile the community.  You notice that most of the people are freemen: tackling the problem of the plague has reduced the need of slaves for labor.\n\nThe city is " + CityControl.city100Corruption + "% corrupt, and its prosperity is " + CityControl.city100Prosperity;
			} 
		}


	}






	void Awake (){
		WorldControl.location = "Aurorum - Downtown"; 
	}

	void Start () 
	{
		DowntownStart ();
	
	}
	
	// Update is called once per frame
	void Update () {
	
	}
}
